Pattern: :1-10
Match: GLY1	HN1
Match: GLY1	N
Match: GLY1	CA
Match: GLY1	C
Match: GLY1	HN2
Match: GLY1	HN3
Match: GLY1	HA1
Match: GLY1	HA2
Match: GLY1	O
Match: VAL2	N
Match: VAL2	CA
Match: VAL2	C
Match: VAL2	HN
Match: VAL2	CB
Match: VAL2	CG1
Match: VAL2	CG2
Match: VAL2	HA
Match: VAL2	HB
Match: VAL2	HG1
Match: VAL2	HG2
Match: VAL2	HG3
Match: VAL2	HG4
Match: VAL2	HG5
Match: VAL2	HG6
Match: VAL2	O
Match: GLN3	N
Match: GLN3	CA
Match: GLN3	C
Match: GLN3	HN
Match: GLN3	CB
Match: GLN3	CG
Match: GLN3	CD
Match: GLN3	NE2
Match: GLN3	HE1
Match: GLN3	HE2
Match: GLN3	OE1
Match: GLN3	HA
Match: GLN3	HB1
Match: GLN3	HB2
Match: GLN3	HG1
Match: GLN3	HG2
Match: GLN3	O
Match: VAL4	N
Match: VAL4	CA
Match: VAL4	C
Match: VAL4	HN
Match: VAL4	CB
Match: VAL4	CG1
Match: VAL4	CG2
Match: VAL4	HA
Match: VAL4	HB
Match: VAL4	HG1
Match: VAL4	HG2
Match: VAL4	HG3
Match: VAL4	HG4
Match: VAL4	HG5
Match: VAL4	HG6
Match: VAL4	O
Match: GLH5	N
Match: GLH5	CA
Match: GLH5	C
Match: GLH5	HN
Match: GLH5	CB
Match: GLH5	CG
Match: GLH5	CD
Match: GLH5	OE1
Match: GLH5	OE2
Match: GLH5	HE1
Match: GLH5	HA
Match: GLH5	HB1
Match: GLH5	HB2
Match: GLH5	HG1
Match: GLH5	HG2
Match: GLH5	O
Match: THR6	N
Match: THR6	CA
Match: THR6	C
Match: THR6	HN
Match: THR6	CB
Match: THR6	OG1
Match: THR6	HG
Match: THR6	CG2
Match: THR6	HA
Match: THR6	HB
Match: THR6	HG1
Match: THR6	HG2
Match: THR6	HG3
Match: THR6	O
Match: ILE7	N
Match: ILE7	CA
Match: ILE7	C
Match: ILE7	HN
Match: ILE7	CB
Match: ILE7	CG1
Match: ILE7	CG2
Match: ILE7	CD1
Match: ILE7	HA
Match: ILE7	HB
Match: ILE7	HG1
Match: ILE7	HG2
Match: ILE7	HG3
Match: ILE7	HG4
Match: ILE7	HG5
Match: ILE7	HD1
Match: ILE7	HD2
Match: ILE7	HD3
Match: ILE7	O
Match: SER8	N
Match: SER8	CA
Match: SER8	C
Match: SER8	HN
Match: SER8	CB
Match: SER8	OG
Match: SER8	HG
Match: SER8	HA
Match: SER8	HB1
Match: SER8	HB2
Match: SER8	O
Match: PRO9	N
Match: PRO9	CA
Match: PRO9	C
Match: PRO9	CB
Match: PRO9	CG
Match: PRO9	CD
Match: PRO9	HA
Match: PRO9	HB1
Match: PRO9	HB2
Match: PRO9	HG1
Match: PRO9	HG2
Match: PRO9	HD1
Match: PRO9	HD2
Match: PRO9	O
Match: GLY10	N
Match: GLY10	CA
Match: GLY10	C
Match: GLY10	HN
Match: GLY10	HA1
Match: GLY10	HA2
Match: GLY10	O
Total: 139 atoms
