include ../../src/config.h


test: duplex_test deform_test reflexive_test gsub_test hashed_test shifts_test \
	sff_test rattle_min_test fd_test gb_test xfin_test gbsa_test gb2_test \
	gb5_test gb8_test gb7_test rattle_md_test rembed_test dhfrndpmtx_test asp_test \
	aspnb_test prm_test cif_test xmin_test netcdf_test variable_14test \
	lmod_test nmode1_test nmode2_test nmode3_test ips_test pbsa_test

testrism:  \
	rism_test rism_md_test rism_dist rism_hnc rism_ion rism_nocut rism_md_pse1 \
	rism_ion-noasymp rism_ion_pse1 rism_ion_pse3 rism_mdiis0 rism_mdiis1 \
	rism_list rism_sp rism_sp2 rism_sp_list rism_xmin

duplex_test::
	@./Run.duplex

deform_test::
	@./Run.deform

reflexive_test::
	@./Run.reflexive

gsub_test::
	@./Run.gsub

hashed_test::
	@./Run.hashed

shifts_test::
	@./Run.shifts

sff_test::
	@./Run.sff

rattle_min_test::
	@./Run.shake

fd_test:: 
	@./Run.fd

gb_test::
	@./Run.gb

xfin_test::
	@./Run.xfin

gbsa_test::
	@./Run.gbsa

gb2_test::
	@./Run.gb2

gb5_test::
	@./Run.gb5

gb7_test::
	@./Run.gb7

gb8_test::
	@./Run.gb8

rattle_md_test::
	@./Run.rattle_md

dg_test::
	@./Run.dg

rembed_test::
	@./Run.rembed

dhfrndpmtx_test::
	@./Run.dhfrndpmtx

asp_test::
	@./Run.asp

aspnb_test::
	@./Run.aspnb

aspgb8_test::
	@./Run.aspgb8

variable_14test::
	@./Run.variable_14

crambin_test::
	@./Run.crambin

prm_test::
	@./Run.prm

cif_test::
	@./Run.cif

xmin_test::
	@./Run.xmin

netcdf_test::
	@./Run.netcdf

lmod_test::
	@./Run.lmod

nmode1_test::
	@./Run.nmode1

nmode2_test::
	@./Run.nmode2

nmode3_test::
	@./Run.nmode3

ips_test::
	@./Run.ips

pbsa_test::
	@./Run.pbsa

rism_test::
	@./Run.rism_min

rism_md_test::
	@./Run.rism_md

rism_hnc::
	@./Run.rism_hnc

rism_list::
	@./Run.rism_list

rism_dist::
	@./Run.rism_dist

rism_ion::
	@./Run.rism_ion

rism_nocut::
	@./Run.rism_md_nocut

rism_md_pse1::
	@./Run.rism_md_pse1

rism_ion-noasymp::
	@./Run.rism_ion-noasymp

rism_ion_pse1::
	@./Run.rism_ion_pse1

rism_ion_pse3::
	@./Run.rism_ion_pse3

rism_sp::
	@./Run.rism_sp

rism_sp2::
	@./Run.rism_sp2

rism_sp_list::
	@./Run.rism_sp_list

rism_mdiis0::
	@./Run.rism_mdiis0

rism_mdiis1::
	@./Run.rism_mdiis1

rism_xmin::
	@./Run.rism_xmin
