.PHONY: test
test: clean
	./Run.emil_pmemd

.PHONY: clean
clean:
	rm -Rf *tmp* a c catch wells.dat test_timings.dat emil.in emilParameters.in mdcrd restrt testWells.dat logfile test.out mdout.emil.[0,1].[0-9] *.stderr.* *.stdout.* *.dif A.dat A gF*.dat *~ lj2_* 
	

