###
#
# Makefile for mr
#
###

AVS_LIBS=	$(AVS_PATH)/lib
AVS_INC=	$(AVS_PATH)/include
NAB_INC=	$(NABHOME)/include
NAB_LIBS=	$(NABHOME)/lib/$(ARCH)
SYM_LIBS=	-L$(SYM_HOME) -lsym
BASELIBS=	-lgeom -lutil -lm $(LASTLIBS)
CFLAGS=		-I$(AVS_INC) -I$(NAB_INC) $(AOPTCFLAGS) $(LOCAL_CFLAGS) $(G)
CFLOWLIBS=	-L$(AVS_LIBS) -lflow_c $(BASELIBS)

ron:	ron.o
	$(CC) $(CFLAGS) -o ron ron.o $(SYM_LIBS) $(CFLOWLIBS)
