# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Chemistry-File-SMILES
version:      0.44
version_from: SMILES.pm
installdirs:  site
requires:
    Chemistry::Bond::Find:         0.21
    Chemistry::Canonicalize:       0.10
    Chemistry::Mol:                0.30
    Chemistry::Ring:               0.15
    List::Util:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
