#!/bin/sh

/bin/rm -f \
TEST_FAILURES.diff \
antechamber/ash/antechamber.out \
antechamber/ash/sqm.in \
antechamber/ash/sqm.out \
antechamber/bondtype/antechamber.out \
antechamber/c60/antechamber.out \
antechamber/charmm/antechamber.out \
antechamber/fluorescein/antechamber.out \
antechamber/fluorescein/sqm.in \
antechamber/fluorescein/sqm.out \
antechamber/fpph/antechamber.out \
antechamber/guanine_amber/antechamber.out \
antechamber/guanine_amber/sqm.in \
antechamber/guanine_amber/sqm.out \
antechamber/residuegen/ala_conf1.esp \
antechamber/residuegen/ala_conf2.esp \
antechamber/residuegen/ANTECHAMBER_AC.AC \
antechamber/residuegen/ANTECHAMBER_AC.AC0 \
antechamber/residuegen/ANTECHAMBER_BOND_TYPE.AC \
antechamber/residuegen/ANTECHAMBER_BOND_TYPE.AC0 \
antechamber/residuegen/antechamber.out \
antechamber/residuegen/ATOMTYPE.INF \
antechamber/residuegen/esout \
antechamber/residuegen/espgen.out \
antechamber/residuegen/NEWPDB.PDB \
antechamber/residuegen/PREP.INF \
antechamber/residuegen/punch \
antechamber/residuegen/QIN \
antechamber/residuegen/qout \
antechamber/residuegen/RESIDUE_GEN_MAINCHAIN.DAT \
antechamber/residuegen/RESIDUE_GEN_RESP.INPUT1 \
antechamber/residuegen/RESIDUE_GEN_RESP.INPUT2 \
antechamber/residuegen/RESIDUE_GEN_RESP.OUTPUT1 \
antechamber/residuegen/RESIDUE_GEN_RESP.OUTPUT2 \
antechamber/residuegen/RESIDUE_GEN_RESPGEN.DAT \
antechamber/residuegen/RESIDUE_GEN.AC \
antechamber/residuegen/residuegen.out \
antechamber/sustiva/antechamber.out \
antechamber/sustiva/leap.log \
antechamber/sustiva/prmtop \
antechamber/sustiva/sqm.in \
antechamber/sustiva/sqm.out \
antechamber/tp/antechamber.out \
antechamber/tp/sqm.out \
leap/ff91.log \
leap/ff94_prm.log \
leap/ff94_prm.out \
leap/ff94.log \
leap/ions91.log \
leap/ions94.log \
leap/leap.log \
leap/lib91.out \
leap/lib94.out \
leap/x.lib \
nab/asp_nm1.out \
nab/asp_nm3.out.tmp \
nab/asp.out \
nab/aspnb.out \
nab/duplex \
nab/fd.pdb \
nab/gbrna.pdb.lpdb \
nab/txmin.out \
ptraj_matrix/1rrb_vac_distcovarmat.dat \
ptraj_matrix/ptraj.out \
ptraj_rmsa/ptraj.out \
rism1d/spc/spc-nacl.sav \
rism1d/spc/spc-nacl.xvv \
rism1d/tip3p/tip3p-nacl.sav \
sleap/14scale/nma1.inpcrd \
sleap/14scale/nma1.prmtop \
sleap/14scale/nma2.inpcrd \
sleap/14scale/nma2.prmtop \
sleap/14scale/test1.out \
sleap/14scale/test2.out \
sleap/addions/1zik_ion.mol2 \
sleap/addions/addion3.out \
sleap/addions/addions.out \
sleap/addions/addions2.pdb \
sleap/addions/hpv_ion.pdb \
sleap/amoeba/amoeba_sol.out \
sleap/amoeba/amoeba.out \
sleap/amoeba/hpv.prmtop \
sleap/amoeba/hpv.xyz \
sleap/amoeba/hpvoct.pdb \
sleap/amoeba/jac_2.prmtop \
sleap/amoeba/jac.xyz \
sleap/amoeba/leap.in \
sleap/bondbydis/leap.in \
sleap/bondbydis/leap.out \
sleap/bondbydis/wy.sdf \
sleap/builder/leap.out \
sleap/builder/wat2.mol2 \
sleap/builder/water.mol2 \
sleap/disulfide/auto.H.out \
sleap/disulfide/auto.out \
sleap/disulfide/crn.H.mol2 \
sleap/disulfide/crn.mol2 \
sleap/disulfide/crn.top \
sleap/disulfide/crn.xyz \
sleap/disulfide/leap.in \
sleap/disulfide/manu.out \
sleap/DNA/132d.mol2 \
sleap/DNA/32d.top \
sleap/DNA/32d.xyz \
sleap/DNA/dna1.out \
sleap/DNA/dna2.out \
sleap/glycam/all.out \
sleap/glycam/leap.in \
sleap/glycam/n.pdb \
sleap/mdlsdf/crown_2.sdf \
sleap/mdlsdf/leap.out \
sleap/molinfo/leap.out \
sleap/offlib/hpv.off \
sleap/offlib/off.out \
sleap/oldleap/ff91/all_amino91.lib \
sleap/oldleap/ff91/all_aminoct91.lib \
sleap/oldleap/ff91/all_aminont91.lib \
sleap/oldleap/ff91/all_nucleic91.lib \
sleap/oldleap/ff94_prm.out \
sleap/oldleap/ff94/all_amino94.lib \
sleap/oldleap/ff94/all_aminoan94.crd \
sleap/oldleap/ff94/all_aminoan94.top \
sleap/oldleap/ff94/all_aminoct94.lib \
sleap/oldleap/ff94/all_aminonc94.crd \
sleap/oldleap/ff94/all_aminonc94.top \
sleap/oldleap/ff94/all_aminont94.lib \
sleap/oldleap/ff94/all_dna94.crd \
sleap/oldleap/ff94/all_dna94.top \
sleap/oldleap/ff94/all_nucleic94.lib \
sleap/oldleap/ff94/all_rna94.crd \
sleap/oldleap/ff94/all_rna94.top \
sleap/oldleap/lib91.out \
sleap/oldleap/lib94.out \
sleap/pdbent/1hpv.mol2 \
sleap/pdbent/leap.out \
sleap/pdbent/mdl_1hpv.mol2 \
sleap/pdbent/pdbent2.out \
sleap/polymer/aa.mol2 \
sleap/polymer/combine.mol2 \
sleap/polymer/impose.mol2 \
sleap/polymer/impose.out \
sleap/polymer/leap.in \
sleap/polymer/leap.out \
sleap/polymer/meoh.mol2 \
sleap/polymer/polymer2.out \
sleap/polymer/sequence.mol2 \
sleap/polymer/zmatrix.out \
sleap/prmtop/box.out \
sleap/prmtop/cap.out \
sleap/prmtop/hpv_cap.top \
sleap/prmtop/hpv_cap.xyz \
sleap/prmtop/hpv.top \
sleap/prmtop/hpv.xyz \
sleap/prmtop/hpvbox.top \
sleap/prmtop/hpvbox.xyz \
sleap/prmtop/leap.out \
sleap/prmtop/pol.out \
sleap/prmtop/ubqpol.top \
sleap/prmtop/ubqpol.xyz \
sleap/propdiol/mol.inpcrd \
sleap/propdiol/mol2.inpcrd \
sleap/propdiol/mol2.prmtop \
sleap/propdiol/test1.out \
sleap/propdiol/test2.out \
sleap/solvate/cap.out \
sleap/solvate/hpvbox_closeness.pdb \
sleap/solvate/hpvbox.pdb \
sleap/solvate/hpvcap.pdb \
sleap/solvate/hpvoct.pdb \
sleap/solvate/hpvoct.top \
sleap/solvate/hpvoct.xyz \
sleap/solvate/hpvshell.pdb \
sleap/solvate/leap.in \
sleap/solvate/oct.out \
sleap/solvate/solvatebox_closeness.out \
sleap/solvate/solvatebox.out \
sleap/solvate/solvateshell.out \
sleap/source/source.out \
sleap/TEST_FAILURES.diff \
sleap/transform/leap.in \
sleap/transform/meoh_trans1.mol2 \
sleap/transform/meoh_trans2.mol2 \
sleap/transform/translate.out \
sleap/tripos/leap.out \
sleap/tripos/wy.mol2 \
sqm/ch3f/ch3f.pm6.go.out \
parmed/chamber_prmtop/final.prmtop \
parmed/chamber_prmtop/prmtop.NBFIX \
parmed/chamber_prmtop/prmtop.new_chg \
parmed/chamber_prmtop/prmtop.new_type \
parmed/chamber_prmtop/parmed.out \
parmed/normal_prmtop/final.prmtop \
parmed/normal_prmtop/prmtop.NBFIX \
parmed/normal_prmtop/prmtop.mbondi3 \
parmed/normal_prmtop/prmtop.new_chg \
parmed/normal_prmtop/trx.frcmod \
parmed/normal_prmtop/parmed.out \
parmed/normal_prmtop/trx.off

find . -name "*.dif" -print0 | xargs -0 /bin/rm -f
