#!/usr/bin/env bash
#
#	Genera el fichro de grid y dock para FB
#__________________________________________________________________________________________________________________________________________
#
#	Se genera la grid (fichero conf y ejecutar)
#
if [ ! -f ${out_grid}"_grid.inp" ];then #si existe la grid no la crea
	echo "Generate Grid ($x $y $z) wait a few minuts "
	echo "File: Input file for grid generation"   						>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "Grid parameter:"												>>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "Center of grid(AA):          "  $x   $y 	$z					>>${out_grid}"_grid.inp"
	echo "Size of grid(AA):              "${gridSizeX}					>>${out_grid}"_grid.inp"
	#echo "Size of grid(AA):              60"							>>${out_grid}"_grid.inp"
	echo "Spacing of grid points(AA):    0.5"							>>${out_grid}"_grid.inp"
	echo "Dielectricity constant:        4.0"							>>${out_grid}"_grid.inp"
	echo "Number of external sidechains: 0"								>>${out_grid}"_grid.inp"
	echo "List of external sidechains:   "								>>${out_grid}"_grid.inp"
	echo "Number of flexible water molecules: 0"						>>${out_grid}"_grid.inp"
	echo "List of flexible Water molecules (Res. ID):"					>>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "Input Filenames:"												>>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "Protein file:               "${CWD}${target}				    >>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "Output Filenames:"											>>${out_grid}"_grid.inp"
	echo "*********************************************************"	>>${out_grid}"_grid.inp"
	echo "VdW Grid:                   "${out_grid}"_s.vdw"				>>${out_grid}"_grid.inp"
	echo "ES Grid:                    "${out_grid}"_l.es"					>>${out_grid}"_grid.inp"
	echo	 "Sidechain file:         "${out_grid}"_g.mol2"				>>${out_grid}"_grid.inp"
	echo "Water file:                 "${out_grid}"_r.mol2"				>>${out_grid}"_grid.inp"
	${path_external_sw}FlexScreen_Biotin/dogrid_32bit_v5 ${out_grid}"_grid.inp" >${out_grid}_g.ucm
fi
#
#	Fichero de dock
#
echo "File: Input file for docking" >${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Docking parameter:">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "nLigand(in database):      1">>${outDock}"_dock.inp"
echo "Range(to be docked):        1    1">>${outDock}"_dock.inp"
echo "nSample:                 100   5    2">>${outDock}"_dock.inp"
#echo "nSample:                 100   20    2">>${outDock}"_dock.inp"
echo "nStep:                   5000  30000  75000">>${outDock}"_dock.inp"
#echo "nStep:                   5000  300000  750000">>${outDock}"_dock.inp"
echo "Temperature(K):             4     3    2.5">>${outDock}"_dock.inp"
echo "Timestep(ps):             300   300  300">>${outDock}"_dock.inp"
echo "nInit:                    10000">>${outDock}"_dock.inp"
echo "Gamma(Mol/kJ):            0.01">>${outDock}"_dock.inp"
echo "driftTerm(1/(ps*K)):      1.0e-6">>${outDock}"_dock.inp"
echo "Center of drift(AA):      "$x"  "$y"  "$z >>${outDock}"_dock.inp"
echo "Random seed:             113 "			>>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Input Filenames:">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Ligand database:            "${CWD}${query} >>${outDock}"_dock.inp" #Nombre query
echo "Sidegroup file:             "${out_grid}"_g.mol2">>${outDock}"_dock.inp"
echo "VdW Grid:                   "${out_grid}"_s.vdw">>${outDock}"_dock.inp"
echo "ES Grid:                    "${out_grid}"_l.es">>${outDock}"_dock.inp"
echo "Flexible Water file:        "${out_grid}"_r.mol2">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Output Filenames:">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Ligand output:             "${out_molec}".mol">>${outDock}"_dock.inp" ##CAMBIARLO
echo "Info output:               "${out_energies}".dat">>${outDock}"_dock.inp"
echo "Energy output:             "${out_energies}".eng">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Simulation-Method">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Energy print-out of current conf. [1 (yes) or 0 (no)]: 0">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Force field parameters:">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Dielectricity constant:       4.0">>${outDock}"_dock.inp"
echo "Atom starting scaling factor: 0.9">>${outDock}"_dock.inp"
echo "Assign SG-flexibility automatic? [1 (yes) or 0 (no)]:  0">>${outDock}"_dock.inp"
echo "Use only orig.lig.conf.? [1 (yes) or 0 (no)]:  0">>${outDock}"_dock.inp"
echo "Number of H-bond Constraints:   0">>${outDock}"_dock.inp"
echo "H-bond constraint Atom ID:      ">>${outDock}"_dock.inp"
echo "Water penalty:      0">>${outDock}"_dock.inp"
echo "5AA:      20">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "Lennard-Jones:    Sigma (nm)  Epsilon (kJ/Mol)">>${outDock}"_dock.inp"
echo "************************************************">>${outDock}"_dock.inp"
echo "C:                  0.356         0.63">>${outDock}"_dock.inp"
echo "H:                  0.178         0.08">>${outDock}"_dock.inp"
echo "O:                  0.285         0.84">>${outDock}"_dock.inp"
echo "S:                  0.356         0.84">>${outDock}"_dock.inp"
echo "N:                  0.29          0.67">>${outDock}"_dock.inp"
echo "I:                  0.35          1.81">>${outDock}"_dock.inp"
echo "Cl:                 0.40          0.494">>${outDock}"_dock.inp"
echo "F:                  0.25          3.01">>${outDock}"_dock.inp"
echo "Br:                 0.41          0.377">>${outDock}"_dock.inp"
echo "Li:                 0.21          0.076">>${outDock}"_dock.inp"
echo "Na:                 0.33          0.012">>${outDock}"_dock.inp"
echo "K:                  0.44          0.002">>${outDock}"_dock.inp"
echo "Mg:                 0.17          3.66">>${outDock}"_dock.inp"
echo "Ca:                 0.24          1.88">>${outDock}"_dock.inp"
echo "Zn:                 0.18          3.66">>${outDock}"_dock.inp"
echo "Dummy:              0.35          0.276">>${outDock}"_dock.inp"
echo "*************************************************">>${outDock}"_dock.inp"
echo "H-Bonds:    C10(kJ/Mol*nm^10)  C12(kJ/Mol*nm^12)">>${outDock}"_dock.inp"
echo "*************************************************">>${outDock}"_dock.inp"
echo "N:               7.696e-6        2.315e-7">>${outDock}"_dock.inp"
echo "O:               7.696e-6        2.315e-7">>${outDock}"_dock.inp"
echo "S:               2.394e-5        1.247e-6">>${outDock}"_dock.inp"
