#! /bin/bash

 for x in `cat list`
 do
    for y in `cat case`
    do
       echo $x.$y
       cd $x/$y
       z=`ls | grep 'Run'`
       ./$z
#      echo "=============================================================="
       cd ..
       cd ..
    done
 done
   
