#!/bin/csh

#setenv AMBERHOME `echo $PWD | sed 's/\// /g' | awk '{for (i=1; i<NF-2; i++) printf "/%s",$i;printf"\n"}'`

echo $AMBERHOME

cat << EOT > leaprc.ARD
source leaprc.ff12pol
aa=sequence {ACE ALA ARG ASP NME}
addions aa Na+ 1 Cl- 1
solvatebox aa POL3BOX 8 
saveamberparmpol aa ARDbox.prmtop ARDbox.crd
quit
EOT

tleap -f leaprc.ARD

cat << EOT > mdineq.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 1, irest = 0,
   ntb = 2, cut = 8,
   ntpr = 100, ntwx = 500, ntwr = 50000,
   nstlim = 100, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0,
   diptau = 9.0, irstdip = 0,
 /

EOT

$AMBERHOME/bin/sander -O -i mdineq.box -p ARDbox.prmtop -c ARDbox.crd \
                         -o ARDbox.mdout0 -inf ARDbox.mdinfo0 \
                      -rdip ARDbox.rstdip0 -r ARDbox.rst0

cat << EOT > mdinrun.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 7, irest = 1,
   ntb = 2, cut = 8,
   ntpr = 1, ntwx = 500, ntwr = 50000,
   nstlim = 50, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0, diptau = 9.0, irstdip = 1,
 /

EOT

$AMBERHOME/bin/sander -O -i mdinrun.box -p ARDbox.prmtop -c ARDbox.rst0 \
                         -o ARDbox.mdout1 -inf ARDbox.mdinfo1 \
                      -rdip ARDbox.rstdip1 -r ARDbox.rst1 \
                      -idip ARDbox.rstdip0 -x ARDbox.trj1

