############################################################
#  	Default Logging Configuration File
#
# You can use a different file by specifying a filename
# with the java.util.logging.config.file system property.  
# For example java -Djava.util.logging.config.file=myfile
############################################################

############################################################
#  	Global properties
############################################################

# "handlers" specifies a comma separated list of log Handler 
# classes.  These handlers will be installed during VM startup.
# Note that these classes must be on the system classpath.
# By default we only configure a ConsoleHandler, which will only
# show messages at the INFO and above levels.
handlers= java.util.logging.FileHandler java.util.logging.ConsoleHandler

# To also add the FileHandler, use the following line instead.
#handlers= java.util.logging.FileHandler, java.util.logging.ConsoleHandler

# Default global logging level.
# This specifies which kinds of events are logged across
# all loggers.  For any given facility this global level
# can be overriden by a facility specific level
# Note that the ConsoleHandler also has a separate level
# setting to limit messages printed to the console.
.level = INFO

############################################################
# Handler specific properties.
# Describes specific configuration info for Handlers.
############################################################

# default file output is in user's home directory.
java.util.logging.FileHandler.pattern = jcart%u.log
java.util.logging.FileHandler.limit = 50000000
java.util.logging.FileHandler.count = 1
#java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter
java.util.logging.FileHandler.formatter = chemaxon.jchem.cartridge.util.SimpleFormatterTh
java.util.logging.FileHandler.level = FINEST

# Limit the message that are printed on the console to INFO and above.
java.util.logging.ConsoleHandler.level = INFO
java.util.logging.ConsoleHandler.formatter = chemaxon.util.logging.SimplestFormatter


############################################################
# Facility specific properties.
# Provides extra control for each logger.
############################################################

# chemaxon.jchem.db.JChemSearch.stats.level = FINE
# chemaxon.jchem.cartridge.rmi.impl.JchemSearchResultImpl.level = FINEST
# chemaxon.jchem.cartridge.level = FINEST
# chemaxon.jchem.level = FINEST
# chemaxon.util.BlockingIntArrayQueue.level = FINEST
chemaxon.jchem.cartridge.ServerControl.level = FINEST
chemaxon.jchem.cartridge.config.level = FINEST
chemaxon.jchem.cartridge.install.level = FINEST
# chx.jchem.cartridge.util.cpools.CommonsDataSource.handlers = java.util.logging.FileHandler
# chx.jchem.cartridge.util.cpools.CommonsDataSource.level = FINEST

############################################################
# Oracle trace logger properties
############################################################
chemaxon.jchem.cartridge.oracleTraceLog.level = WARNING
chemaxon.jchem.cartridge.oracleTraceLog.FileHandler.pattern = trace%u.log
chemaxon.jchem.cartridge.oracleTraceLog.FileHandler.formatter = chemaxon.util.logging.SimplestFormatter
