#!/bin/sh

# This should be every file that may be created by the tests
# remove them all individually, since the list may be too long
# for rm.

/bin/rm -f 4096wat/logfile
/bin/rm -f 4096wat/mdout.column_fft
/bin/rm -f 4096wat/mdout.pure_wat
/bin/rm -f 4096wat/mdout.pure_wat_nmr_temp
/bin/rm -f 4096wat/mdout.vrand
/bin/rm -f 4096wat_oct/logfile
/bin/rm -f 4096wat_oct/mdcrd.pure_wat_oct
/bin/rm -f 4096wat_oct/mdout.pure_wat_oct
/bin/rm -f LES/LES.crd
/bin/rm -f LES/LES.prmtop
/bin/rm -f LES/md.LES.out
/bin/rm -f LES/mdcrd
/bin/rm -f LES/output_addles
/bin/rm -f LES_CUT/md.LES.out
/bin/rm -f LES_GB/les.gb1.diffcrd.out
/bin/rm -f LES_GB/les.gb1.samecrd.out
/bin/rm -f LES_GB/les.gb5.samecrd.out
/bin/rm -f LES_GB/les.gb7.rdt.out
/bin/rm -f LES_GB/les.gb7.samecrd.out
/bin/rm -f LES_TEMP/2temp.out
/bin/rm -f LES_noPME/md.out
/bin/rm -f LES_noPME/md.rdiel.out
/bin/rm -f PIMD/full_cmd_water/equilib/CMD_position.dat
/bin/rm -f PIMD/full_cmd_water/equilib/CMD_velocity.dat
/bin/rm -f PIMD/full_cmd_water/equilib/NHC.dat
/bin/rm -f PIMD/full_cmd_water/equilib/cmd.out
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead1.mdcrd
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead1.mdinfo
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead1.out
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead1.rst
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead2.mdcrd
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead2.mdinfo
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead2.out
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead2.rst
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead3.mdcrd
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead3.mdinfo
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead3.out
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead3.rst
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead4.mdcrd
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead4.mdinfo
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead4.out
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_bead4.rst
/bin/rm -f PIMD/full_cmd_water/equilib/cmd_sander.out
/bin/rm -f PIMD/full_cmd_water/restart/CMD_position.dat
/bin/rm -f PIMD/full_cmd_water/restart/CMD_velocity.dat
/bin/rm -f PIMD/full_cmd_water/restart/NHC.dat
/bin/rm -f PIMD/full_cmd_water/restart/cmd.out
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead1.mdcrd
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead1.mdinfo
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead1.out
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead1.rst
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead2.mdcrd
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead2.mdinfo
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead2.out
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead2.rst
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead3.mdcrd
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead3.mdinfo
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead3.out
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead3.rst
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead4.mdcrd
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead4.mdinfo
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead4.out
/bin/rm -f PIMD/full_cmd_water/restart/cmd_bead4.rst
/bin/rm -f PIMD/full_cmd_water/restart/cmd_sander.out
/bin/rm -f PIMD/full_cmd_water/start/CMD_position.dat
/bin/rm -f PIMD/full_cmd_water/start/CMD_velocity.dat
/bin/rm -f PIMD/full_cmd_water/start/NHC.dat
/bin/rm -f PIMD/full_cmd_water/start/cmd.out
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead1.mdcrd
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead1.mdinfo
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead1.out
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead1.rst
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead2.mdcrd
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead2.mdinfo
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead2.out
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead2.rst
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead3.mdcrd
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead3.mdinfo
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead3.out
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead3.rst
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead4.mdcrd
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead4.mdinfo
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead4.out
/bin/rm -f PIMD/full_cmd_water/start/cmd_bead4.rst
/bin/rm -f PIMD/full_cmd_water/start/cmd_sander.out
/bin/rm -f PIMD/full_nmpimd_water/NHC.dat
/bin/rm -f PIMD/full_nmpimd_water/bead1.mdcrd
/bin/rm -f PIMD/full_nmpimd_water/bead1.mdinfo
/bin/rm -f PIMD/full_nmpimd_water/bead1.out
/bin/rm -f PIMD/full_nmpimd_water/bead1.rst
/bin/rm -f PIMD/full_nmpimd_water/bead2.mdcrd
/bin/rm -f PIMD/full_nmpimd_water/bead2.mdinfo
/bin/rm -f PIMD/full_nmpimd_water/bead2.out
/bin/rm -f PIMD/full_nmpimd_water/bead2.rst
/bin/rm -f PIMD/full_nmpimd_water/bead3.mdcrd
/bin/rm -f PIMD/full_nmpimd_water/bead3.mdinfo
/bin/rm -f PIMD/full_nmpimd_water/bead3.out
/bin/rm -f PIMD/full_nmpimd_water/bead3.rst
/bin/rm -f PIMD/full_nmpimd_water/bead4.mdcrd
/bin/rm -f PIMD/full_nmpimd_water/bead4.mdinfo
/bin/rm -f PIMD/full_nmpimd_water/bead4.out
/bin/rm -f PIMD/full_nmpimd_water/bead4.rst
/bin/rm -f PIMD/full_nmpimd_water/nmpimd.out
/bin/rm -f PIMD/full_nmpimd_water/sander.out
/bin/rm -f PIMD/full_pimd_amoeba/bead1.mdinfo
/bin/rm -f PIMD/full_pimd_amoeba/bead1.out
/bin/rm -f PIMD/full_pimd_amoeba/bead1.rst
/bin/rm -f PIMD/full_pimd_amoeba/bead2.mdinfo
/bin/rm -f PIMD/full_pimd_amoeba/bead2.out
/bin/rm -f PIMD/full_pimd_amoeba/bead2.rst
/bin/rm -f PIMD/full_pimd_amoeba/bead3.mdinfo
/bin/rm -f PIMD/full_pimd_amoeba/bead3.out
/bin/rm -f PIMD/full_pimd_amoeba/bead3.rst
/bin/rm -f PIMD/full_pimd_amoeba/bead4.mdinfo
/bin/rm -f PIMD/full_pimd_amoeba/bead4.out
/bin/rm -f PIMD/full_pimd_amoeba/bead4.rst
/bin/rm -f PIMD/full_pimd_amoeba/pimd_amoeba.out
/bin/rm -f PIMD/full_pimd_amoeba/sander.out
/bin/rm -f PIMD/full_pimd_ln_water/bead1.mdcrd
/bin/rm -f PIMD/full_pimd_ln_water/bead1.mdinfo
/bin/rm -f PIMD/full_pimd_ln_water/bead1.out
/bin/rm -f PIMD/full_pimd_ln_water/bead1.rst
/bin/rm -f PIMD/full_pimd_ln_water/bead2.mdcrd
/bin/rm -f PIMD/full_pimd_ln_water/bead2.mdinfo
/bin/rm -f PIMD/full_pimd_ln_water/bead2.out
/bin/rm -f PIMD/full_pimd_ln_water/bead2.rst
/bin/rm -f PIMD/full_pimd_ln_water/bead3.mdcrd
/bin/rm -f PIMD/full_pimd_ln_water/bead3.mdinfo
/bin/rm -f PIMD/full_pimd_ln_water/bead3.out
/bin/rm -f PIMD/full_pimd_ln_water/bead3.rst
/bin/rm -f PIMD/full_pimd_ln_water/bead4.mdcrd
/bin/rm -f PIMD/full_pimd_ln_water/bead4.mdinfo
/bin/rm -f PIMD/full_pimd_ln_water/bead4.out
/bin/rm -f PIMD/full_pimd_ln_water/bead4.rst
/bin/rm -f PIMD/full_pimd_ln_water/pimd_ln.out
/bin/rm -f PIMD/full_pimd_ln_water/sander.out
/bin/rm -f PIMD/full_pimd_nhc_water/NHC.dat
/bin/rm -f PIMD/full_pimd_nhc_water/bead1.mdcrd
/bin/rm -f PIMD/full_pimd_nhc_water/bead1.mdinfo
/bin/rm -f PIMD/full_pimd_nhc_water/bead1.out
/bin/rm -f PIMD/full_pimd_nhc_water/bead1.rst
/bin/rm -f PIMD/full_pimd_nhc_water/bead2.mdcrd
/bin/rm -f PIMD/full_pimd_nhc_water/bead2.mdinfo
/bin/rm -f PIMD/full_pimd_nhc_water/bead2.out
/bin/rm -f PIMD/full_pimd_nhc_water/bead2.rst
/bin/rm -f PIMD/full_pimd_nhc_water/bead3.mdcrd
/bin/rm -f PIMD/full_pimd_nhc_water/bead3.mdinfo
/bin/rm -f PIMD/full_pimd_nhc_water/bead3.out
/bin/rm -f PIMD/full_pimd_nhc_water/bead3.rst
/bin/rm -f PIMD/full_pimd_nhc_water/bead4.mdcrd
/bin/rm -f PIMD/full_pimd_nhc_water/bead4.mdinfo
/bin/rm -f PIMD/full_pimd_nhc_water/bead4.out
/bin/rm -f PIMD/full_pimd_nhc_water/bead4.rst
/bin/rm -f PIMD/full_pimd_nhc_water/pimd_nhc.out
/bin/rm -f PIMD/full_pimd_nhc_water/sander.out
/bin/rm -f PIMD/full_pimd_ntp_water/NHC.dat
/bin/rm -f PIMD/full_pimd_ntp_water/bead1.mdcrd
/bin/rm -f PIMD/full_pimd_ntp_water/bead1.mdinfo
/bin/rm -f PIMD/full_pimd_ntp_water/bead1.out
/bin/rm -f PIMD/full_pimd_ntp_water/bead1.rst
/bin/rm -f PIMD/full_pimd_ntp_water/bead2.mdcrd
/bin/rm -f PIMD/full_pimd_ntp_water/bead2.mdinfo
/bin/rm -f PIMD/full_pimd_ntp_water/bead2.out
/bin/rm -f PIMD/full_pimd_ntp_water/bead2.rst
/bin/rm -f PIMD/full_pimd_ntp_water/bead3.mdcrd
/bin/rm -f PIMD/full_pimd_ntp_water/bead3.mdinfo
/bin/rm -f PIMD/full_pimd_ntp_water/bead3.out
/bin/rm -f PIMD/full_pimd_ntp_water/bead3.rst
/bin/rm -f PIMD/full_pimd_ntp_water/bead4.mdcrd
/bin/rm -f PIMD/full_pimd_ntp_water/bead4.mdinfo
/bin/rm -f PIMD/full_pimd_ntp_water/bead4.out
/bin/rm -f PIMD/full_pimd_ntp_water/bead4.rst
/bin/rm -f PIMD/full_pimd_ntp_water/pimd_ntp.out
/bin/rm -f PIMD/full_pimd_ntp_water/sander.out
/bin/rm -f PIMD/full_rpmd_water/bead1.mdcrd
/bin/rm -f PIMD/full_rpmd_water/bead1.mdinfo
/bin/rm -f PIMD/full_rpmd_water/bead1.mdvel
/bin/rm -f PIMD/full_rpmd_water/bead1.out
/bin/rm -f PIMD/full_rpmd_water/bead1.rst
/bin/rm -f PIMD/full_rpmd_water/bead2.mdcrd
/bin/rm -f PIMD/full_rpmd_water/bead2.mdinfo
/bin/rm -f PIMD/full_rpmd_water/bead2.mdvel
/bin/rm -f PIMD/full_rpmd_water/bead2.out
/bin/rm -f PIMD/full_rpmd_water/bead2.rst
/bin/rm -f PIMD/full_rpmd_water/bead3.mdcrd
/bin/rm -f PIMD/full_rpmd_water/bead3.mdinfo
/bin/rm -f PIMD/full_rpmd_water/bead3.mdvel
/bin/rm -f PIMD/full_rpmd_water/bead3.out
/bin/rm -f PIMD/full_rpmd_water/bead3.rst
/bin/rm -f PIMD/full_rpmd_water/bead4.mdcrd
/bin/rm -f PIMD/full_rpmd_water/bead4.mdinfo
/bin/rm -f PIMD/full_rpmd_water/bead4.mdvel
/bin/rm -f PIMD/full_rpmd_water/bead4.out
/bin/rm -f PIMD/full_rpmd_water/bead4.rst
/bin/rm -f PIMD/full_rpmd_water/rpmd.out
/bin/rm -f PIMD/part_cmd_water/equilib/CMD_position.dat
/bin/rm -f PIMD/part_cmd_water/equilib/CMD_velocity.dat
/bin/rm -f PIMD/part_cmd_water/equilib/NHC.dat
/bin/rm -f PIMD/part_cmd_water/equilib/addles.out
/bin/rm -f PIMD/part_cmd_water/equilib/cmd.out
/bin/rm -f PIMD/part_cmd_water/equilib/fort.277
/bin/rm -f PIMD/part_cmd_water/equilib/h2o_les.crd
/bin/rm -f PIMD/part_cmd_water/equilib/h2o_les.rst
/bin/rm -f PIMD/part_cmd_water/equilib/h2o_les.top
/bin/rm -f PIMD/part_cmd_water/equilib/mdinfo
/bin/rm -f PIMD/part_cmd_water/restart/CMD_position.dat
/bin/rm -f PIMD/part_cmd_water/restart/CMD_velocity.dat
/bin/rm -f PIMD/part_cmd_water/restart/NHC.dat
/bin/rm -f PIMD/part_cmd_water/restart/cmd.out
/bin/rm -f PIMD/part_cmd_water/restart/fort.277
/bin/rm -f PIMD/part_cmd_water/restart/h2o_les.rst
/bin/rm -f PIMD/part_cmd_water/restart/mdinfo
/bin/rm -f PIMD/part_cmd_water/start/CMD_position.dat
/bin/rm -f PIMD/part_cmd_water/start/CMD_velocity.dat
/bin/rm -f PIMD/part_cmd_water/start/NHC.dat
/bin/rm -f PIMD/part_cmd_water/start/cmd.out
/bin/rm -f PIMD/part_cmd_water/start/fort.277
/bin/rm -f PIMD/part_cmd_water/start/h2o_les.rst
/bin/rm -f PIMD/part_cmd_water/start/mdinfo
/bin/rm -f PIMD/part_nmpimd_helium/NHC.dat
/bin/rm -f PIMD/part_nmpimd_helium/fort.277
/bin/rm -f PIMD/part_nmpimd_helium/hef_pimd.out
/bin/rm -f PIMD/part_nmpimd_helium/mdcrd
/bin/rm -f PIMD/part_nmpimd_helium/mdinfo
/bin/rm -f PIMD/part_nmpimd_helium/restrt
/bin/rm -f PIMD/part_nmpimd_ntp/NHC.dat
/bin/rm -f PIMD/part_nmpimd_ntp/butane_p24.mdcrd
/bin/rm -f PIMD/part_nmpimd_ntp/butane_p24.rst
/bin/rm -f PIMD/part_nmpimd_ntp/fort.277
/bin/rm -f PIMD/part_nmpimd_ntp/mdinfo
/bin/rm -f PIMD/part_nmpimd_ntp/ntp_nmpimd.out
/bin/rm -f PIMD/part_nmpimd_water/NHC.dat
/bin/rm -f PIMD/part_nmpimd_water/addles.out
/bin/rm -f PIMD/part_nmpimd_water/dummy
/bin/rm -f PIMD/part_nmpimd_water/h2o_les.crd
/bin/rm -f PIMD/part_nmpimd_water/h2o_les.top
/bin/rm -f PIMD/part_nmpimd_water/mdinfo
/bin/rm -f PIMD/part_nmpimd_water/nmpimd.in
/bin/rm -f PIMD/part_nmpimd_water/nmpimd.out
/bin/rm -f PIMD/part_nmpimd_water/restrt
/bin/rm -f PIMD/part_pimd_helium/NHC.dat
/bin/rm -f PIMD/part_pimd_helium/fort.277
/bin/rm -f PIMD/part_pimd_helium/hef_pimd.out
/bin/rm -f PIMD/part_pimd_helium/mdcrd
/bin/rm -f PIMD/part_pimd_helium/mdinfo
/bin/rm -f PIMD/part_pimd_helium/restrt
/bin/rm -f PIMD/part_pimd_spcfw/addles.out
/bin/rm -f PIMD/part_pimd_spcfw/fort.277
/bin/rm -f PIMD/part_pimd_spcfw/mdinfo
/bin/rm -f PIMD/part_pimd_spcfw/spcfw_pimd.mdcrd
/bin/rm -f PIMD/part_pimd_spcfw/spcfw_pimd.out
/bin/rm -f PIMD/part_pimd_spcfw/spcfw_pimd.rst
/bin/rm -f PIMD/part_pimd_spcfw/spcfw_pimd.top
/bin/rm -f PIMD/part_pimd_spcfw/spcfw_pimd.xyz
/bin/rm -f PIMD/part_pimd_water/addles.out
/bin/rm -f PIMD/part_pimd_water/dummy
/bin/rm -f PIMD/part_pimd_water/h2o_les.mdcrd
/bin/rm -f PIMD/part_pimd_water/h2o_les.rst
/bin/rm -f PIMD/part_pimd_water/mdinfo
/bin/rm -f PIMD/part_pimd_water/pimd.in
/bin/rm -f PIMD/part_pimd_water/pimd.out
/bin/rm -f PIMD/part_rpmd_water/addles.out
/bin/rm -f PIMD/part_rpmd_water/fort.277
/bin/rm -f PIMD/part_rpmd_water/mdcrd
/bin/rm -f PIMD/part_rpmd_water/mdinfo
/bin/rm -f PIMD/part_rpmd_water/mdvel
/bin/rm -f PIMD/part_rpmd_water/restrt
/bin/rm -f PIMD/part_rpmd_water/spcfw_rpmd.out
/bin/rm -f PIMD/part_rpmd_water/spcfw_rpmd.top
/bin/rm -f PIMD/part_rpmd_water/spcfw_rpmd.xyz
/bin/rm -f adenine/mdout.adenine
/bin/rm -f alp/logfile
/bin/rm -f alp/mdout.alp
/bin/rm -f alpb_trx/logfile
/bin/rm -f alpb_trx/mdout.trxox
/bin/rm -f alpb_trx/mdout.trxox.nogbsa
/bin/rm -f amoeba_formbox/amoeba_formbox.mdout
/bin/rm -f amoeba_gb1/mdout.amoeba_gb1
/bin/rm -f amoeba_jac/amoeba_jac.mdout
/bin/rm -f amoeba_wat1/amoeba_wat1.out
/bin/rm -f amoeba_wat2/amoeba_wat2.out
/bin/rm -f amoeba_wat2/ntpverlet
/bin/rm -f bintraj/bintraj.out
/bin/rm -f bintraj/mdin
/bin/rm -f bintraj/mdinfo
/bin/rm -f bintraj/mdtrj.nc
/bin/rm -f bintraj/nc_headers
/bin/rm -f bintraj/restrt
/bin/rm -f campTI/camp.p0
/bin/rm -f campTI/camp.p1
/bin/rm -f chamber/md_engine/dhfr/logfile
/bin/rm -f chamber/md_engine/dhfr/mdout.dhfr_charmm
/bin/rm -f chamber/md_engine/dhfr/mdout.dhfr_charmm.min
/bin/rm -f chamber/md_engine/dhfr_cmap/logfile
/bin/rm -f chamber/md_engine/dhfr_cmap/mdout.dhfr_charmm
/bin/rm -f chamber/md_engine/dhfr_cmap_pbc/logfile
/bin/rm -f chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm.md
/bin/rm -f chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm.min
/bin/rm -f chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm_noshake.md
/bin/rm -f chamber/md_engine/dhfr_cmap_pbc/mdout.dhfr_charmm_noshake.min
/bin/rm -f circ_dna/logfile
/bin/rm -f circ_dna/mdout.circdna
/bin/rm -f cnstph/explicit/cpout
/bin/rm -f cnstph/explicit/cpout.dif
/bin/rm -f cnstph/explicit/mdout
/bin/rm -f cnstph/explicit/mdout.dif
/bin/rm -f cnstph/implicit/cpout
/bin/rm -f cnstph/implicit/mdout
/bin/rm -f cnstph_remd/ph4.cpout.000.dif
/bin/rm -f cnstph_remd/rem.log
/bin/rm -f cytosine/cytosine.out
/bin/rm -f cytosine/logfile
/bin/rm -f dhfr/logfile
/bin/rm -f dhfr/mdout.dhfr
/bin/rm -f dhfr/mdout.dhfr.lmodxmin
/bin/rm -f dhfr/mdout.dhfr.min
/bin/rm -f dhfr/mdout.dhfr.min_prcg
/bin/rm -f dhfr/mdout.dhfr.min_prcg.dif
/bin/rm -f dhfr/mdout.dhfr.noboxinfo
/bin/rm -f dhfr/mdout.dhfr.noshake
/bin/rm -f dmp/mdout.dmp
/bin/rm -f dna_pol/mdout.dna_pol
/bin/rm -f emil/emil_multisander_gbsa/logfile.000
/bin/rm -f emil/emil_multisander_gbsa/logfile.001
/bin/rm -f emil/emil_pmemd_gbsa/emil.stderr.0.0
/bin/rm -f emil/emil_pmemd_gbsa/emil.stderr.0.1
/bin/rm -f emil/emil_pmemd_gbsa/emil.stderr.0.9
/bin/rm -f emil/emil_pmemd_gbsa/emil.stdout.dummy
/bin/rm -f emil/emil_pmemd_gbsa/emilParameters.in
/bin/rm -f emil/emil_pmemd_gbsa/logfile
/bin/rm -f emil/emil_pmemd_gbsa/mdcrd
/bin/rm -f emil/emil_pmemd_gbsa/mdin
/bin/rm -f emil/emil_pmemd_gbsa/restrt
/bin/rm -f emil/emil_pmemd_gbsa/test_timings.dat
/bin/rm -f emil/emil_pmemd_gbsa/wells.dat
/bin/rm -f emil/emil_pmemd_tip3p/logfile
/bin/rm -f emil/emil_pmemd_tip3p/mdcrd
/bin/rm -f emil/emil_pmemd_tip3p/restrt
/bin/rm -f emil/emil_pmemd_tip3p/test_timings.dat
/bin/rm -f emil/emil_pmemd_tip3p/wells.dat
/bin/rm -f emil/emil_pmemd_tip3p/emil.stderr.0.1
/bin/rm -f emil/emil_pmemd_tip3p/emil.stderr.0.5
/bin/rm -f emil/emil_pmemd_tip3p/emil.stderr.0.9
/bin/rm -f emil/emil_pmemd_tip3p/emilParameters.in
/bin/rm -f emil/emil_sander_tip3p/emil.stderr.0.1
/bin/rm -f emil/emil_sander_tip3p/emil.stderr.0.5
/bin/rm -f emil/emil_sander_tip3p/emil.stderr.0.9
/bin/rm -f emil/emil_sander_tip3p/emilParameters.in
/bin/rm -f emil/emil_sander_gbsa/emil.stderr.0.0
/bin/rm -f emil/emil_sander_gbsa/emil.stderr.0.1
/bin/rm -f emil/emil_sander_gbsa/emil.stderr.0.9
/bin/rm -f emil/emil_sander_gbsa/emilParameters.in
/bin/rm -f emil/emil_sander_gbsa/mdcrd
/bin/rm -f emil/emil_sander_gbsa/restrt
/bin/rm -f emil/emil_sander_gbsa/test_timings.dat
/bin/rm -f emil/emil_sander_gbsa/wells.dat
/bin/rm -f emil/emil_sander_tip3p/mdcrd
/bin/rm -f emil/emil_sander_tip3p/restrt
/bin/rm -f emil/emil_sander_tip3p/test_timings.dat
/bin/rm -f emil/emil_sander_tip3p/wells.dat
/bin/rm -f evb/malon_bond_umb_GAFF/evbout
/bin/rm -f evb/malon_bond_umb_GAFF/mdcrd
/bin/rm -f evb/malon_bond_umb_GAFF/mp.out
/bin/rm -f evb/malon_bond_umb_GAFF/mr.out
/bin/rm -f evb/malon_bond_umb_GAFF/numprocs.awk
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY/evbout
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY/mdcrd
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY/mp.out
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY/mr.out
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY/numprocs.awk
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY_XVDW/evbout
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mdcrd
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mp.out
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY_XVDW/mr.out
/bin/rm -f evb/malon_bond_umb_GAFF_MORSIFY_XVDW/numprocs.awk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/evbout
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mdcrd
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mdinfo
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mp.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mp.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mr.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/mr.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG/numprocs.awk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/NHC.dat
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/evbout
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/fort.1001
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/fort.277
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mdcrd
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mdinfo
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mp_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mp_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mr_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/mr_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_nmpimd_full/numprocs.awk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/evbout
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/fort.277
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mdcrd
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mdinfo
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mp_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mp_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mr_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/mr_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_ld_full/numprocs.awk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/NHC.dat
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/evbout
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/fort.1001
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/fort.277
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mdcrd
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mdinfo
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mp_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mp_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mr_les.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/mr_les.rst
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full/numprocs.awk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/NHC.dat
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.4
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.8
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.1001
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.277
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mdcrd
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.4.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.8.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.4.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.8.out
/bin/rm -f evb/malon_bond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/numprocs.awk
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/NHC.dat
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.4
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/evbout-.8
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.1001
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/fort.277
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mdcrd
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.4.out
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mp_les-.8.out
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.4.out
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/mr_les-.8.out
/bin/rm -f evb/malon_dbond_umb_dg_UFF_3DG_pimd_nhc_full_TI-MASS/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF/mp.out
/bin/rm -f evb/malon_dbonds_umb_GAFF/mr.out
/bin/rm -f evb/malon_dbonds_umb_GAFF/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY/mp.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY/mr.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mp.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/mr.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mp.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/mr.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_nmpimd_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_ld_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_EXP-XCH_pimd_nhc_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mp.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/mr.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_nmpimd_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_ld_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_XVDW_GAUSS-XCH_pimd_nhc_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_nmpimd_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_ld_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/evbout
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/fort.1001
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/fort.277
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mdcrd
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mp_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/mr_les.rst
/bin/rm -f evb/malon_dbonds_umb_GAFF_MORSIFY_pimd_nhc_full/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/evbout
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/fort.1001
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/fort.277
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mdcrd
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_2D-PMF/numprocs.awk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/NHC.dat
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/evbout
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/fort.1001
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/fort.277
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeP_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeR_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/malonaldehydeTS_35.fchk
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mdcrd
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mp_les.out
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/mr_les.out
/bin/rm -f evb/malon_dbonds_umb_dg_UFF_3DG_qi_full_corrF/numprocs.awk
/bin/rm -f evb/malon_emap_GAFF_MORSIFY/evbout
/bin/rm -f evb/malon_emap_GAFF_MORSIFY/mdcrd
/bin/rm -f evb/malon_emap_GAFF_MORSIFY/mp.out
/bin/rm -f evb/malon_emap_GAFF_MORSIFY/mr.out
/bin/rm -f evb/malon_emap_GAFF_MORSIFY/numprocs.awk
/bin/rm -f evb/malon_emap_GAFF_MORSIFY_XVDW/evbout
/bin/rm -f evb/malon_emap_GAFF_MORSIFY_XVDW/mdcrd
/bin/rm -f evb/malon_emap_GAFF_MORSIFY_XVDW/mp.out
/bin/rm -f evb/malon_emap_GAFF_MORSIFY_XVDW/mr.out
/bin/rm -f evb/malon_emap_GAFF_MORSIFY_XVDW/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/evbout
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/mdcrd
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/mdinfo
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/po.out
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/po.rst
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/poh.out
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/poh.rst
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_3DG/pyridone_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/irc_minusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/irc_minusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/irc_plusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/irc_plusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/onehalfP_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/onehalfR_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG/pyridone_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_minusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_minusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_plusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/irc_plusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/onehalfP_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/onehalfR_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full/pyridone_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_minusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_minusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_plusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/irc_plusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/onehalfP_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/onehalfR_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_nmpimd_full_TST-freqf/pyridone_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_minusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_minusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_plusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/irc_plusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/onehalfP_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/onehalfR_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_ld_full/pyridone_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/2hydroxypyridine_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/2hydroxypyridine_TS_56_vtight.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_minusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_minusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_plusonefourth_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/irc_plusonehalf_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/numprocs.awk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/onehalfP_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/onehalfR_56.fchk
/bin/rm -f evb/poh_dbonds_umb_dg_UFF_9DG_pimd_nhc_full/pyridone_56.fchk
/bin/rm -f gact_ips/mdout.ips
/bin/rm -f gact_ips/mdout.ips_dfft
/bin/rm -f gact_ips/mdout.ips_sgld
/bin/rm -f gact_ips/mdout.ips_vacuum
/bin/rm -f gact_ips/mdout.ipsnve
/bin/rm -f gb1_cox2/cox2.out
/bin/rm -f gb1_cox2/logfile
/bin/rm -f gb2_trx/logfile
/bin/rm -f gb2_trx/mdout.trxox
/bin/rm -f gb2_trx/mdout.trxox.nogbsa
/bin/rm -f gb7_trx/logfile
/bin/rm -f gb7_trx/mdout.trxox
/bin/rm -f gb7_trx/mdout.trxox_md
/bin/rm -f gb8_trx/mdout.trxox
/bin/rm -f gb8_trx/mdout.trxox_md
/bin/rm -f gbneck2nu_test/mdout.1hji_md
/bin/rm -f gb_rna/logfile
/bin/rm -f gb_rna/mdout.gbrna
/bin/rm -f gb_rna/mdout.gbrna.ips
/bin/rm -f gb_rna/mdout.gbrna.ln
/bin/rm -f gb_rna/mdout.gbrna.min
/bin/rm -f gb_rna/mdout.gbrna.sgld
/bin/rm -f gbsa_xfin/mdout.gbsa
/bin/rm -f idecomp1/decomp.out
/bin/rm -f idecomp4/decomp.out
/bin/rm -f jar/dist_vs_t
/bin/rm -f jar/mdout.jar
/bin/rm -f jar_multi/dist_vs_t.000
/bin/rm -f jar_multi/dist_vs_t.001
/bin/rm -f jar_multi/mdout.jar.000
/bin/rm -f jar_multi/mdout.jar.001
/bin/rm -f mmpbsa_py/01_Generalized_Born/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/02_Poisson_Boltzmann/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/02_Poisson_Boltzmann/FINAL_RESULTS_MMPBSA.dat.dif
/bin/rm -f mmpbsa_py/03_Alanine_Scanning/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/04_Per_Residue_Decomp/FINAL_DECOMP_MMPBSA.dat
/bin/rm -f mmpbsa_py/04_Per_Residue_Decomp/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/05_Pairwise_Decomp/FINAL_DECOMP_MMPBSA.dat
/bin/rm -f mmpbsa_py/05_Pairwise_Decomp/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/06_NAB_Nmode/FINAL_RESULTS_MMPBSA.dat
/bin/rm -f mmpbsa_py/07_Comprehensive/FINAL_DECOMP_MMPBSA.dat
/bin/rm -f mmpbsa_py/07_Comprehensive/FINAL_DECOMP_MMPBSA_2.dat
/bin/rm -f mmpbsa_py/07_Comprehensive/FINAL_RESULTS_MMPBSA_1.dat
/bin/rm -f mmpbsa_py/07_Comprehensive/FINAL_RESULTS_MMPBSA_2.dat
/bin/rm -f mmpbsa_py/08_Stability/FINAL_DECOMP_MMPBSA1.dat
/bin/rm -f mmpbsa_py/08_Stability/FINAL_DECOMP_MMPBSA2.dat
/bin/rm -f mmpbsa_py/08_Stability/FINAL_DECOMP_MMPBSA2.dat.dif
/bin/rm -f mmpbsa_py/08_Stability/FINAL_RESULTS_MMPBSA1.dat
/bin/rm -f mmpbsa_py/08_Stability/FINAL_RESULTS_MMPBSA2.dat
/bin/rm -f mmpbsa_py/08_Stability/FINAL_RESULTS_MMPBSA2.dat.dif
/bin/rm -f mtmdtest/mtmdtest.mdcrd
/bin/rm -f mtmdtest/mtmdtest.out
/bin/rm -f newton_raph/nmd_min.out
/bin/rm -f nmode/lmode.head
/bin/rm -f nmode/lvibs.out
/bin/rm -f nmode/vecs
/bin/rm -f nmode/vibs.out
/bin/rm -f nmode/vibsr.out
/bin/rm -f noesy/noesy.out
/bin/rm -f nonper/mdout.belly
/bin/rm -f nonper/mdout.belly.mask
/bin/rm -f nonper/mdout.cap
/bin/rm -f nonper/mdout.min
/bin/rm -f nonper/mdout.nocut
/bin/rm -f nonper/mdout.nonper
/bin/rm -f pcsa/stem.csa.o
/bin/rm -f pcsa/stem.csa2.o
/bin/rm -f pcsa/stem.csa_min.o
/bin/rm -f pcsa/stem.dip.o
/bin/rm -f pheMTI/out.0
/bin/rm -f pheMTI/out.1
/bin/rm -f pheMTI/out.lambda0.p0
/bin/rm -f pheMTI/out.lambda1.p0
/bin/rm -f plane_plane_restraint/dinuc_pln_vs_t
/bin/rm -f plane_plane_restraint/dinuc_plpt_vs_t
/bin/rm -f plane_plane_restraint/mdout.dinucAU_pln
/bin/rm -f plane_plane_restraint/mdout.dinucAU_plpt
/bin/rm -f polarizable_water/mdout.polwat
/bin/rm -f qmmm2/1-2-ethanediol_PM3CARB1/ethanediol_md.out
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq1
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq2
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_aq2_NUMER_DERIV
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_lnk_dis_neg
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_lnk_method2
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_mmcorr
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb1_qmewald2
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_MD_ntb2
/bin/rm -f qmmm2/1NLN_periodic_lnk_atoms/mdout.1NLN_min
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_auto
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspev
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspevd
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dspevx
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyev
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyevd
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_dsyevr
/bin/rm -f qmmm2/1NLN_test_diagonalizers/mdout.1NLN_internal
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.imaged
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.imaged_md
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center_bigqmcut_md
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.img_center_md
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme_qmewald
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_periodic/mdout.notimaged_md_pme_qmewald_lowmem
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_qmcut/MG_QM_water_MM.out
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_qmcut/MG_QM_water_MM_MD.out
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_qmcut_ADDMM/MG_QM_water_MM.out
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_qmcut_ADDMM/MG_QM_water_MM_MD.out
/bin/rm -f qmmm2/MG_QM_water_MM_AM1_qmcut_lowmem/MG_QM_water_MM_MD.out
/bin/rm -f qmmm2/PM3-MAIS/hcl_wat.mdcrd
/bin/rm -f qmmm2/PM3-MAIS/hcl_wat.mdout
/bin/rm -f qmmm2/PM3-MAIS/zundel.mdcrd
/bin/rm -f qmmm2/PM3-MAIS/zundel.mdout
/bin/rm -f qmmm2/PM3-MMX/ammonia_dimer.out
/bin/rm -f qmmm2/PM3-MMX/crambin_md_pm3mmx.out
/bin/rm -f qmmm2/PM3-MMX/formic_acid_dimer.out
/bin/rm -f qmmm2/PM3-MMX/water_dimer.out
/bin/rm -f qmmm2/crambin/crambin.out
/bin/rm -f qmmm2/crambin/crambin_md.out
/bin/rm -f qmmm2/crambin/crambin_md_hot_start.out
/bin/rm -f qmmm2/crambin/mdcrd
/bin/rm -f qmmm2/crambin/mdvel
/bin/rm -f qmmm2/crambin/restrt
/bin/rm -f qmmm2/crambin_2/crambin.out
/bin/rm -f qmmm2/crambin_2/crambin_md.out
/bin/rm -f qmmm2/crambin_2/crambin_md_calc_mulliken.out
/bin/rm -f qmmm2/crambin_2/crambin_md_qmgb2.out
/bin/rm -f qmmm2/crambin_2/crambin_md_qmgb2_alpb.out
/bin/rm -f qmmm2/crambin_2/crambin_md_qmgb2_aq1.out
/bin/rm -f qmmm2/crambin_2/crambin_md_qmgb2_aq2.out
/bin/rm -f qmmm2/crambin_2/crambin_md_qmgb2_saltcon.out
/bin/rm -f qmmm2/crambin_PM6/crambin.out
/bin/rm -f qmmm2/crambin_PM6/crambin_md.out
/bin/rm -f qmmm2/crambin_PM6/mdcrd
/bin/rm -f qmmm2/crambin_PM6/mdvel
/bin/rm -f qmmm2/crambin_PM6/restrt
/bin/rm -f qmmm2/input_validation/invalid_atom_ids.out
/bin/rm -f qmmm2/input_validation/non-unique.out
/bin/rm -f qmmm2/lysine_AM1/lysine.out
/bin/rm -f qmmm2/lysine_AM1/lysine_md.out
/bin/rm -f qmmm2/lysine_MNDO/lysine.out
/bin/rm -f qmmm2/lysine_MNDO/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3/lysine.out
/bin/rm -f qmmm2/lysine_PM3/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3/lysine_md_lnk_dis_neg.out
/bin/rm -f qmmm2/lysine_PM3/lysine_md_lnk_method_2.out
/bin/rm -f qmmm2/lysine_PM3/lysine_md_qmmm_int0.out
/bin/rm -f qmmm2/lysine_PM3/lysine_md_qmmm_int2.out
/bin/rm -f qmmm2/lysine_PM3_calc_dipole/lysine.out
/bin/rm -f qmmm2/lysine_PM3_calc_dipole/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3_calc_mulliken/lysine.out
/bin/rm -f qmmm2/lysine_PM3_calc_mulliken/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3_qmgb0/lysine.out
/bin/rm -f qmmm2/lysine_PM3_qmgb0/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_adjust_q1.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_adjust_q2.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_igb2.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_igb5.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_igb7.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2/lysine_md_lnk_dis_neg.out
/bin/rm -f qmmm2/lysine_PM3_qmgb2_alpb/lysine_md.out
/bin/rm -f qmmm2/lysine_PM6/lysine.out
/bin/rm -f qmmm2/lysine_PM6/lysine_md.out
/bin/rm -f qmmm2/pure_QM_MD/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD/nma.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_0.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_2.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_3.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_4.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_5.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_6.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_diag_routine_7.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_qmgb0.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_qmgb1.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_qmgb2.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_qmgb2_saltcon.out
/bin/rm -f qmmm2/pure_QM_MD/nma_md_qmgb3.out
/bin/rm -f qmmm2/pure_QM_MD_AM1/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD_AM1/nma.out
/bin/rm -f qmmm2/pure_QM_MD_AM1/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_AM1_ADDMM/nma.out
/bin/rm -f qmmm2/pure_QM_MD_AM1_ADDMM/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_MNDO/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD_MNDO/nma.out
/bin/rm -f qmmm2/pure_QM_MD_MNDO/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_NUMER_DERIV/nma.out
/bin/rm -f qmmm2/pure_QM_MD_NUMER_DERIV/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb0.out
/bin/rm -f qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb2.out
/bin/rm -f qmmm2/pure_QM_MD_NUMER_DERIV/nma_md_qmgb2_saltcon.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGMNDO/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGMNDO/nma.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGMNDO/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGPM3/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGPM3/nma.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGPM3/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGPM3_08/nma.out
/bin/rm -f qmmm2/pure_QM_MD_PDDGPM3_08/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_PM6/nma.out
/bin/rm -f qmmm2/pure_QM_MD_PM6/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_RM1/C6H4FCL_md.out
/bin/rm -f qmmm2/pure_QM_MD_RM1/nma.out
/bin/rm -f qmmm2/pure_QM_MD_RM1/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_shake/nma_md.out
/bin/rm -f qmmm2/pure_QM_MD_tight_p/nma.out
/bin/rm -f qmmm2/pure_QM_MD_tight_p/nma_md.out
/bin/rm -f qmmm2/tip3p_cap/tip3p_cap.out
/bin/rm -f qmmm2/tip3p_cap/tip3p_cap_md.out
/bin/rm -f qmmm2/tip3p_cap/tip3p_cap_md_shake.out
/bin/rm -f qmmm2/tip3p_cap/tip3p_cap_md_shake_qmshake_off.out
/bin/rm -f qmmm2/variable_solvent/mdout.1NLN_MD_ntb1_vsolv
/bin/rm -f qmmm2/variable_solvent/mg_periodic_vsolv_wat.out
/bin/rm -f qmmm2/xcrd_build_test/mdout.oct_nma_imaged
/bin/rm -f qmmm2/xcrd_build_test/mdout.oct_nma_noimage
/bin/rm -f qmmm2/xcrd_build_test/mdout.ortho_qmewald0
/bin/rm -f qmmm2/xcrd_build_test/mdout.truncoct_qmewald0
/bin/rm -f qmmm2/znme2/znme2.znb.md.out
/bin/rm -f qmmm2/znme2/znme2.znb.min.out
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/DISP.CHEK
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq1
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq1_disp
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_aq2
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_lnk_dis_neg
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_lnk_method2
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb1_qmewald2
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_MD_ntb2
/bin/rm -f qmmm_DFTB/1NLN_periodic_lnk_atoms_DFTB/mdout.1NLN_min
/bin/rm -f qmmm_DFTB/3rd-order/ala8/mdout_PA
/bin/rm -f qmmm_DFTB/3rd-order/ala8/mdout_PR
/bin/rm -f qmmm_DFTB/3rd-order/water/mdout
/bin/rm -f qmmm_DFTB/3rd-order/water/mdout.read_file
/bin/rm -f qmmm_DFTB/3rd-order/water/mdout.read_mdin
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.imaged
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.imaged_md
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center_bigqmcut_md
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.img_center_md
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md_pme
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_periodic/mdout.notimaged_md_pme_qmewald
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut/MG_QM_water_MM.out
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut/MG_QM_water_MM_MD.out
/bin/rm -f qmmm_DFTB/MG_QM_water_MM_DFTB_qmcut_lowmem/MG_QM_water_MM_MD.out
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1_link_atoms
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb1_qmewald2
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_ewald_ntb2
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb1
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms_aq1
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_link_atoms_aq2
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_qmewald2
/bin/rm -f qmmm_DFTB/aladip_tip3p_ewaldpme/mdout.aladip_pme_ntb2_telec
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_calc_mulliken.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_alpb.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_aq1.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_aq2.out
/bin/rm -f qmmm_DFTB/crambin_2_DFTB/crambin_md_qmgb2_saltcon.out
/bin/rm -f qmmm_DFTB/crambin_DFTB/crambin.out
/bin/rm -f qmmm_DFTB/crambin_DFTB/crambin_md.out
/bin/rm -f qmmm_DFTB/crambin_DFTB/crambin_md_hot_start.out
/bin/rm -f qmmm_DFTB/crambin_DFTB/mdcrd
/bin/rm -f qmmm_DFTB/crambin_DFTB/mdvel
/bin/rm -f qmmm_DFTB/crambin_DFTB/restrt
/bin/rm -f qmmm_DFTB/lysine_DFTB/lysine.out
/bin/rm -f qmmm_DFTB/lysine_DFTB/lysine_md.out
/bin/rm -f qmmm_DFTB/lysine_DFTB/lysine_md_lnk_dis_neg.out
/bin/rm -f qmmm_DFTB/lysine_DFTB/lysine_md_lnk_method2.out
/bin/rm -f qmmm_DFTB/lysine_DFTB/lysine_md_qmmm_int0.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_calc_mulliken/lysine.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_calc_mulliken/lysine_md.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb0/lysine.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb0/lysine_md.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_adjust_q1.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_adjust_q2.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb2.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb5.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2/lysine_md_igb7.out
/bin/rm -f qmmm_DFTB/lysine_DFTB_qmgb2_alpb/lysine_md.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/DISP.CHEK
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_disper.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_md.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb0.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb1.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb2.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_DFTB/nma_md_qmgb2_saltcon.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_shake_DFTB/nma_md.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_tight_p_DFTB/nma.out
/bin/rm -f qmmm_DFTB/pure_QM_MD_tight_p_DFTB/nma_md.out
/bin/rm -f qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap.out
/bin/rm -f qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md.out
/bin/rm -f qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md_shake.out
/bin/rm -f qmmm_DFTB/tip3p_cap_DFTB/tip3p_cap_md_shake_qmshake_off.out
/bin/rm -f abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.frc
/bin/rm -f abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.idrst
/bin/rm -f abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.out
/bin/rm -f abfqmmm/abfqmmm_water_sp/abfqmmm_water_sp.pdb
/bin/rm -f abfqmmm/abfqmmm_water_md/abfqmmm_water_md.frc
/bin/rm -f abfqmmm/abfqmmm_water_md/abfqmmm_water_md.idrst
/bin/rm -f abfqmmm/abfqmmm_water_md/abfqmmm_water_md.out
/bin/rm -f abfqmmm/abfqmmm_water_md/abfqmmm_water_md.pdb
/bin/rm -f abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.frc
/bin/rm -f abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.idrst
/bin/rm -f abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.out
/bin/rm -f abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.pdb
/bin/rm -f abfqmmm/abfqmmm_dmpoh_md/abfqmmm_dmpoh_md.rst
/bin/rm -f abfqmmm/adqmmm_water_md/adqmmm_water_md.frc
/bin/rm -f abfqmmm/adqmmm_water_md/adqmmm_water_md.idrst
/bin/rm -f abfqmmm/adqmmm_water_md/adqmmm_water_md.out
/bin/rm -f abfqmmm/adqmmm_water_md/adqmmm_water_md.pdb
/bin/rm -f abfqmmm/hotspot_water_md/hotspot_water_md.frc
/bin/rm -f abfqmmm/hotspot_water_md/hotspot_water_md.idrst
/bin/rm -f abfqmmm/hotspot_water_md/hotspot_water_md.out
/bin/rm -f abfqmmm/hotspot_water_md/hotspot_water_md.pdb
/bin/rm -f rdc/gcg.csa.o
/bin/rm -f rdc/gcg.csa_min.o
/bin/rm -f rdc/gcg.dip.o
/bin/rm -f rem_gb_2rep/rem.log
/bin/rm -f rem_gb_2rep/rem.out.000
/bin/rm -f rem_gb_2rep/rem.out.001
/bin/rm -f rem_gb_4rep/rem.log
/bin/rm -f rem_gb_4rep/rem.out.000
/bin/rm -f rem_gb_4rep/rem.out.001
/bin/rm -f rem_gb_4rep/rem.out.002
/bin/rm -f rem_gb_4rep/rem.out.003
/bin/rm -f rem_hybrid/rem.log
/bin/rm -f rem_hybrid/rem.out.000
/bin/rm -f rem_hybrid/rem.out.001
/bin/rm -f rem_wat/rem.log
/bin/rm -f rem_wat/rem.out.000
/bin/rm -f rem_wat/rem.out.001
/bin/rm -f rem_wat/reminfo.000
/bin/rm -f rem_wat/reminfo.001
/bin/rm -f rism3d/ala/ala.dist.out
/bin/rm -f rism3d/ala/ala.hnc.out
/bin/rm -f rism3d/ala/ala.out
/bin/rm -f rism3d/ala/ala.resize.out
/bin/rm -f rism3d/ala/ala.resize.out.dif
/bin/rm -f rism3d/ala/cuv.H1.5.dx
/bin/rm -f rism3d/ala/cuv.O.5.dx
/bin/rm -f rism3d/ala/guv.H1.5.dx
/bin/rm -f rism3d/ala/guv.O.5.dx
/bin/rm -f rism3d/ala/huv.H1.5.dx
/bin/rm -f rism3d/ala/huv.O.5.dx
/bin/rm -f rism3d/phosphate/ph1-nacl.out
/bin/rm -f rism3d/phosphate/ph1.out
/bin/rm -f rism3d/phosphate/ph10-nacl.out
/bin/rm -f rism3d/phosphate/ph10.out
/bin/rm -f rism3d/phosphate/ph2.out
/bin/rm -f rism3d/phosphate/ph20.out
/bin/rm -f sander_pbsa_decpw/mdout.pbsa_decpw
/bin/rm -f sander_pbsa_decres/mdout.pbsa_decres
/bin/rm -f sander_pbsa_delphi/mdout.1az6.min
/bin/rm -f sander_pbsa_dmp/mdout.dmp.min
/bin/rm -f sander_pbsa_ipb2/mdout.110D.min
/bin/rm -f sander_pbsa_lpb/mdout.min_bc5_solv1
/bin/rm -f sander_pbsa_lpb/mdout.min_bc5_solv2
/bin/rm -f sander_pbsa_lpb/mdout.min_bc5_solv3
/bin/rm -f sander_pbsa_lpb/mdout.min_bc5_solv4
/bin/rm -f sander_pbsa_lpb/mdout.min_bc6_solv1
/bin/rm -f sander_pbsa_lpb/mdout.min_bc6_solv3
/bin/rm -f sander_pbsa_lpb/mdout.min_bc6_solv4
/bin/rm -f sander_pbsa_radi/Br.out
/bin/rm -f sander_pbsa_radi/Ca.out
/bin/rm -f sander_pbsa_radi/Cl.out
/bin/rm -f sander_pbsa_radi/Cs.out
/bin/rm -f sander_pbsa_radi/F.out
/bin/rm -f sander_pbsa_radi/I.out
/bin/rm -f sander_pbsa_radi/IM.out
/bin/rm -f sander_pbsa_radi/K.out
/bin/rm -f sander_pbsa_radi/Li.out
/bin/rm -f sander_pbsa_radi/MG.out
/bin/rm -f sander_pbsa_radi/Na.out
/bin/rm -f sander_pbsa_radi/Rb.out
/bin/rm -f sander_pbsa_radi/Zn.out
/bin/rm -f sander_pbsa_radi/alabk.out
/bin/rm -f sander_pbsa_radi/arg.out
/bin/rm -f sander_pbsa_radi/ash.out
/bin/rm -f sander_pbsa_radi/asn.out
/bin/rm -f sander_pbsa_radi/asp.out
/bin/rm -f sander_pbsa_radi/cym.out
/bin/rm -f sander_pbsa_radi/cys.out
/bin/rm -f sander_pbsa_radi/cyx.out
/bin/rm -f sander_pbsa_radi/da.out
/bin/rm -f sander_pbsa_radi/da3p.out
/bin/rm -f sander_pbsa_radi/da5p.out
/bin/rm -f sander_pbsa_radi/danp.out
/bin/rm -f sander_pbsa_radi/dap.out
/bin/rm -f sander_pbsa_radi/dc.out
/bin/rm -f sander_pbsa_radi/dg.out
/bin/rm -f sander_pbsa_radi/dt.out
/bin/rm -f sander_pbsa_radi/glh.out
/bin/rm -f sander_pbsa_radi/gln.out
/bin/rm -f sander_pbsa_radi/glu.out
/bin/rm -f sander_pbsa_radi/glybk.out
/bin/rm -f sander_pbsa_radi/hid.out
/bin/rm -f sander_pbsa_radi/hie.out
/bin/rm -f sander_pbsa_radi/hip.out
/bin/rm -f sander_pbsa_radi/ile.out
/bin/rm -f sander_pbsa_radi/leu.out
/bin/rm -f sander_pbsa_radi/lyn.out
/bin/rm -f sander_pbsa_radi/lys.out
/bin/rm -f sander_pbsa_radi/met.out
/bin/rm -f sander_pbsa_radi/nhe.out
/bin/rm -f sander_pbsa_radi/nma.out
/bin/rm -f sander_pbsa_radi/phe.out
/bin/rm -f sander_pbsa_radi/probk.out
/bin/rm -f sander_pbsa_radi/ra3p.out
/bin/rm -f sander_pbsa_radi/ra5p.out
/bin/rm -f sander_pbsa_radi/ranp.out
/bin/rm -f sander_pbsa_radi/rap.out
/bin/rm -f sander_pbsa_radi/ru.out
/bin/rm -f sander_pbsa_radi/ser.out
/bin/rm -f sander_pbsa_radi/thr.out
/bin/rm -f sander_pbsa_radi/tp3.out
/bin/rm -f sander_pbsa_radi/trp.out
/bin/rm -f sander_pbsa_radi/tyr.out
/bin/rm -f sander_pbsa_radi/val.out
/bin/rm -f sander_pbsa_tsr/mdout.tsrb.min
/bin/rm -f sodium/md1.o
/bin/rm -f softcore/complex/out.0
/bin/rm -f softcore/complex/out.1
/bin/rm -f softcore/complex/restrt.0
/bin/rm -f softcore/complex/restrt.1
/bin/rm -f softcore/complex_rst/out.0
/bin/rm -f softcore/complex_rst/out.1
/bin/rm -f softcore/complex_rst/restrt.0
/bin/rm -f softcore/complex_rst/restrt.1
/bin/rm -f softcore/dynlmb/out.0
/bin/rm -f softcore/dynlmb/out.1
/bin/rm -f softcore/dynlmb/restrt.0
/bin/rm -f softcore/dynlmb/restrt.1
/bin/rm -f softcore/electro/out.0
/bin/rm -f softcore/electro/out.1
/bin/rm -f softcore/electro/restrt.0
/bin/rm -f softcore/electro/restrt.1
/bin/rm -f softcore/min/out.0
/bin/rm -f softcore/min/out.1
/bin/rm -f softcore/min/restrt.0
/bin/rm -f softcore/min/restrt.1
/bin/rm -f softcore/short_md/out.0
/bin/rm -f softcore/short_md/out.1
/bin/rm -f softcore/short_md/out2.0
/bin/rm -f softcore/short_md/out2.1
/bin/rm -f softcore/short_md/restrt.0
/bin/rm -f softcore/short_md/restrt.1
/bin/rm -f softcore/short_md/restrt2.0
/bin/rm -f softcore/short_md/restrt2.1
/bin/rm -f tgtmd/PME/tgtmd.out
/bin/rm -f tgtmd/change_target.ntr/tgtmd.out
/bin/rm -f tgtmd/change_target.ntr/tgtmd.out.dif
/bin/rm -f tgtmd/change_target.rms/tgtmd.out
/bin/rm -f tgtmd/change_target/tgtmd.out
/bin/rm -f tgtmd/conserve_ene/tgtmd.out
/bin/rm -f tgtmd/minimize/tgtmin.out
/bin/rm -f ti_decomp/ti_decomp_1.out
/bin/rm -f ti_decomp/ti_decomp_2.out
/bin/rm -f ti_eth2meth_gas/out.eth_ic1_k1_c0.5
/bin/rm -f ti_eth2meth_gas/out.eth_ic1_k1_c0.5.methane
/bin/rm -f ti_eth2meth_gas/out.eth_ic1_k6_c0.5
/bin/rm -f ti_eth2meth_gas/out.eth_ic1_k6_c0.5.methane
/bin/rm -f ti_ggcc/out_icfe1_klambda_1_clambda_0.5.p1
/bin/rm -f ti_ggcc/out_icfe1_klambda_1_clambda_0.5.p2
/bin/rm -f ti_ggcc/out_icfe1_klambda_6_clambda_0.5.p1
/bin/rm -f ti_mass/pent_LES_PIMD/NHC.dat
/bin/rm -f ti_mass/pent_LES_PIMD/addles.out
/bin/rm -f ti_mass/pent_LES_PIMD/mdinfo
/bin/rm -f ti_mass/pent_LES_PIMD/pent-TI_les.top
/bin/rm -f ti_mass/pent_LES_PIMD/pent_les.crd
/bin/rm -f ti_mass/pent_LES_PIMD/pimd.out
/bin/rm -f ti_mass/pent_LES_PIMD/restrt
/bin/rm -f ti_mass/pentadiene/bead1.out
/bin/rm -f ti_mass/pentadiene/bead1.rst
/bin/rm -f ti_mass/pentadiene/bead2.out
/bin/rm -f ti_mass/pentadiene/bead2.rst
/bin/rm -f ti_mass/pentadiene/inf.1
/bin/rm -f ti_mass/pentadiene/inf.2
/bin/rm -f ti_mass/pentadiene/pimd.out
/bin/rm -f tip4p/logfile
/bin/rm -f tip4p/mdout.tip4p
/bin/rm -f tip4p/mdout.tip4p_nve
/bin/rm -f tip5p/logfile
/bin/rm -f tip5p/mdout.tip5p
/bin/rm -f tip5p/mdout.tip5p_nve
/bin/rm -f trajene/mdcrd.out
/bin/rm -f trajene/trajene.out
/bin/rm -f trajene_box/mdcrd.out
/bin/rm -f trajene_box/trajene.out
/bin/rm -f trajene_netcdf/mdcrd.out.nc
/bin/rm -f trajene_netcdf/trajene.out
/bin/rm -f trx/logfile
/bin/rm -f trx/mdout.trx
/bin/rm -f trx/mdout.trx.cpln
/bin/rm -f trx/mdout.trx.cpln.pmemd
/bin/rm -f ubiquitin/mdcrd
/bin/rm -f ubiquitin/mden
/bin/rm -f ubiquitin/mdout.ubiquitin
/bin/rm -f ubiquitin/mdvel
/bin/rm -f ubiquitin/restrt
/bin/rm -f ubiquitin/rstdip
/bin/rm -f umbrella/chi_vs_t
/bin/rm -f umbrella/mdout.umbrella
/bin/rm -f variable_14/logfile
/bin/rm -f variable_14/variable_14_igb1.mdout
/bin/rm -f variable_14/variable_14_ntb1.mdout
/bin/rm -f iapbs_radi/*.out iapbs_radi/mdin*
/bin/rm -f iwrap2/dummy
/bin/rm -f iwrap2/mdin
/bin/rm -f iwrap2/mdinfo
/bin/rm -f neb-testcases/neb_*/mdin 
/bin/rm -f neb-testcases/neb_*/*.inf 
/bin/rm -f neb-testcases/neb_*/*.mdcrd 
/bin/rm -f neb-testcases/neb_*/*.rst 
/bin/rm -f neb-testcases/neb_*/*.out
/bin/rm -f gact_ips/logfile
/bin/rm -f gb8_trx/logfile
/bin/rm -f gbneck2nu_test/logfile
/bin/rm -f gbsa_xfin/logfile
/bin/rm -f h_rem/rem.pmemd.MPI.log
/bin/rm -f h_rem/rem.sander.MPI.log
/bin/rm -f logs/test_amber_parallel/2011-10-13_21-27-03.diff
/bin/rm -f logs/test_amber_parallel/2011-10-13_21-27-03.log
/bin/rm -f logs/test_amber_serial/2011-10-13_14-56-40.diff
/bin/rm -f logs/test_amber_serial/2011-10-13_14-56-40.log
/bin/rm -f nc_restart/MD_ncrestart_write/md.in
/bin/rm -f nc_restart/MD_ncrestart_write/md.nc
/bin/rm -f nc_restart/MD_ncrestart_write/md.out
/bin/rm -f nc_restart/MD_ncrestart_write/mdinfo
/bin/rm -f nc_restart/MD_ncrestart_write/ncmd.rst7
/bin/rm -f nc_restart/Min_ncrestart_write/mdinfo
/bin/rm -f nc_restart/Min_ncrestart_write/min.in
/bin/rm -f nc_restart/Min_ncrestart_write/min.nc
/bin/rm -f nc_restart/Min_ncrestart_write/min.out
/bin/rm -f nc_restart/Min_ncrestart_write/ncmin.rst7
/bin/rm -f nc_restart/refMD_ncrestart/md.in
/bin/rm -f nc_restart/refMD_ncrestart/md.nc
/bin/rm -f nc_restart/refMD_ncrestart/mdinfo
/bin/rm -f nc_restart/restartMD.ntx1/md.in
/bin/rm -f nc_restart/restartMD.ntx1/md.nc
/bin/rm -f nc_restart/restartMD.ntx1/md1.rst7
/bin/rm -f nc_restart/restartMD.ntx1/mdinfo
/bin/rm -f nc_restart/restartMD.ntx5/md.in
/bin/rm -f nc_restart/restartMD.ntx5/md.nc
/bin/rm -f nc_restart/restartMD.ntx5/md1.rst7
/bin/rm -f nc_restart/restartMD.ntx5/mdinfo
/bin/rm -f crg_reloc/1-4elec/*.out
/bin/rm -f crg_reloc/cyt/*.out
/bin/rm -f crg_reloc/misc/*.out
/bin/rm -f crg_reloc/water/*.out

# Now get rid of all *.dif files and ddtmp.* files. If the dacdif prefix
# is changed, change that here.

find . -name "*.dif" -print0 | xargs -0 /bin/rm 2>/dev/null
find . -name "ddtmp.*" -print0 | xargs -0 /bin/rm 2>/dev/null
/bin/rm -f TEST_FAILURES.diff
