#!/bin/csh

set AMBERHOME=`echo $PWD | sed 's/\// /g' | awk '{for (i=1; i<NF-2; i++) printf "/%s",$i;printf"\n"}'`

echo $AMBERHOME

cat << EOT > leaprc.ubq
source leaprc.ff12pol
aa=loadpdb ubiquitin.pdb
addions aa Na+ 0
addions aa Cl- 0
solvatebox aa POL3BOX 8 
saveamberparmpol aa ubqbox.prmtop ubqbox.crd
quit
EOT

tleap -f leaprc.ubq

cat << EOT > mdineq.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 1, irest = 0,
   ntb = 2, cut = 8,
   ntpr = 100, ntwx = 500, ntwr = 50000,
   nstlim = 100, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0,
   diptau = 9.0, irstdip = 0,
 /
EOT

$AMBERHOME/bin/sander -O -i mdineq.box -p ubqbox.prmtop -c ubqbox.crd \
                         -o ubqbox.mdout0 -inf ubqbox.mdinfo0 \
                      -rdip ubqbox.rstdip0 -r ubqbox.rst0

cat << EOT > mdinrun.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 7, irest = 1,
   ntb = 2, cut = 8,
   ntpr = 1, ntwx = 500, ntwr = 50000,
   nstlim = 50, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0, diptau = 9.0, irstdip = 1,
 /
EOT

$AMBERHOME/bin/sander -O -i mdinrun.box -p ubqbox.prmtop -c ubqbox.rst0 \
                         -o ubqbox.mdout1 -inf ubqbox.mdinfo1 \
                      -rdip ubqbox.rstdip1 -r ubqbox.rst1 \
                      -idip ubqbox.rstdip0 -x ubqbox.trj1

