
#line 3 "<nabout>"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define dgoconst const
#else
#define dgoconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (dgo_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((dgo_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE dgorestart(dgoin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(dgo_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct dgo_buffer_state *YY_BUFFER_STATE;
#endif

extern int dgoleng;

extern FILE *dgoin, *dgoout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define dgoless(n) \
	do \
		{ \
		/* Undo effects of setting up dgotext. */ \
        int dgoless_macro_arg = (n); \
        YY_LESS_LINENO(dgoless_macro_arg);\
		*dgo_cp = (dgo_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(dgo_c_buf_p) = dgo_cp = dgo_bp + dgoless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up dgotext again */ \
		} \
	while ( 0 )

#define unput(c) dgounput( c, (dgotext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int dgo_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct dgo_buffer_state
	{
	FILE *dgo_input_file;

	char *dgo_ch_buf;		/* input buffer */
	char *dgo_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	dgo_size_t dgo_buf_size;

	/* Number of characters read into dgo_ch_buf, not including EOB
	 * characters.
	 */
	int dgo_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int dgo_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int dgo_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int dgo_at_bol;

    int dgo_bs_lineno; /**< The line count. */
    int dgo_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int dgo_fill_buffer;

	int dgo_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via dgorestart()), so that the user can continue scanning by
	 * just pointing dgoin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t dgo_buffer_stack_top = 0; /**< index of top of stack. */
static size_t dgo_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * dgo_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (dgo_buffer_stack) \
                          ? (dgo_buffer_stack)[(dgo_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (dgo_buffer_stack)[(dgo_buffer_stack_top)]

/* dgo_hold_char holds the character lost when dgotext is formed. */
static char dgo_hold_char;
static int dgo_n_chars;		/* number of characters read into dgo_ch_buf */
int dgoleng;

/* Points to current character in buffer. */
static char *dgo_c_buf_p = (char *) 0;
static int dgo_init = 0;		/* whether we need to initialize */
static int dgo_start = 0;	/* start state number */

/* Flag which is used to allow dgowrap()'s to do buffer switches
 * instead of setting up a fresh dgoin.  A bit of a hack ...
 */
static int dgo_did_buffer_switch_on_eof;

void dgorestart (FILE *input_file  );
void dgo_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE dgo_create_buffer (FILE *file,int size  );
void dgo_delete_buffer (YY_BUFFER_STATE b  );
void dgo_flush_buffer (YY_BUFFER_STATE b  );
void dgopush_buffer_state (YY_BUFFER_STATE new_buffer  );
void dgopop_buffer_state (void );

static void dgoensure_buffer_stack (void );
static void dgo_load_buffer_state (void );
static void dgo_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER dgo_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE dgo_scan_buffer (char *base,dgo_size_t size  );
YY_BUFFER_STATE dgo_scan_string (dgoconst char *dgo_str  );
YY_BUFFER_STATE dgo_scan_bytes (dgoconst char *bytes,int len  );

void *dgoalloc (dgo_size_t  );
void *dgorealloc (void *,dgo_size_t  );
void dgofree (void *  );

#define dgo_new_buffer dgo_create_buffer

#define dgo_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        dgoensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dgo_create_buffer(dgoin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->dgo_is_interactive = is_interactive; \
	}

#define dgo_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        dgoensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            dgo_create_buffer(dgoin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->dgo_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->dgo_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *dgoin = (FILE *) 0, *dgoout = (FILE *) 0;

typedef int dgo_state_type;

extern int dgolineno;

int dgolineno = 1;

extern char *dgotext;
#define dgotext_ptr dgotext

static dgo_state_type dgo_get_previous_state (void );
static dgo_state_type dgo_try_NUL_trans (dgo_state_type current_state  );
static int dgo_get_next_buffer (void );
static void dgo_fatal_error (dgoconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up dgotext.
 */
#define YY_DO_BEFORE_ACTION \
	(dgotext_ptr) = dgo_bp; \
	dgoleng = (size_t) (dgo_cp - dgo_bp); \
	(dgo_hold_char) = *dgo_cp; \
	*dgo_cp = '\0'; \
	(dgo_c_buf_p) = dgo_cp;

#define YY_NUM_RULES 24
#define YY_END_OF_BUFFER 25
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct dgo_trans_info
	{
	flex_int32_t dgo_verify;
	flex_int32_t dgo_nxt;
	};
static dgoconst flex_int16_t dgo_accept[145] =
    {   0,
        0,    0,   25,   23,   22,   22,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   22,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
        4,    0,    0,   13,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    2,    0,    5,    0,    0,    0,    0,

        0,    0,   12,    0,    0,    0,   10,    0,    0,    0,
       20,    0,    0,    8,    0,    0,    0,   11,    7,   14,
        0,    0,    0,    0,    0,   21,    0,    0,    0,    0,
        0,   18,   15,    0,    0,   16,   17,    0,    3,    0,
       19,    6,    9,    0
    } ;

static dgoconst flex_int32_t dgo_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    5,    6,    7,    5,    1,    8,    8,    9,
        9,   10,    9,    9,    9,    9,    9,    1,    1,    1,
       11,    1,    1,    1,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   12,   13,   14,   15,

       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,    1,   34,
        1,   35,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static dgoconst flex_int32_t dgo_meta[36] =
    {   0,
        1,    2,    2,    2,    3,    4,    3,    3,    3,    3,
        1,    1,    1,    1,    1,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static dgoconst flex_int16_t dgo_base[158] =
    {   0,
        0,   29,  232,  233,    5,   34,    2,  219,  215,    0,
      216,   27,  197,  211,   48,   46,   73,  202,  201,  200,
      203,  207,  202,  193,  198,  187,  190,   17,  191,  189,
      190,  182,  188,  195,  178,  193,  175,    1,    9,  195,
      176,   17,  185,  188,  177,  173,  172,  187,  185,  183,
      163,   44,  180,   46,  180,  177,  181,  172,    0,    0,
      157,  159,    0,   60,  164,  159,  167,   62,  170,  153,
      157,   74,    0,  154,    0,   76,  165,  152,  154,    0,
        0,   77,   78,    0,    0,   79,  159,  143,   83,  162,
      145,  163,    0,    0,   90,    0,   88,  149,  144,  143,

       94,   97,    0,    0,  128,  144,  100,  107,  108,  128,
        0,  105,  112,  115,  116,  122,  123,  120,  127,    0,
      101,  127,  108,    0,   71,  131,  138,    0,   91,  139,
        0,  233,    0,  140,   78,    0,  233,  137,    0,    0,
      233,  144,    0,  233,  154,  158,  161,   81,  164,  167,
       67,   64,   46,   43,   31,  170,   16
    } ;

static dgoconst flex_int16_t dgo_def[158] =
    {   0,
      145,  145,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  146,  147,
      144,  144,  148,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  149,  144,  150,  144,  144,  144,  144,  146,
      147,  144,  144,  148,  151,  144,  144,  144,  144,  144,
      144,  144,  152,  149,  144,  150,  144,  144,  144,  144,

      144,  144,  151,  153,  144,  144,  144,  144,  144,  144,
      152,  144,  144,  144,  144,  144,  144,  144,  144,  153,
      144,  144,  144,  154,  144,  144,  144,  155,  144,  144,
      156,  144,  154,  144,  144,  155,  144,  144,  156,  157,
      144,  144,  157,    0,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144
    } ;

static dgoconst flex_int16_t dgo_nxt[269] =
    {   0,
      144,    5,    6,    5,   59,    5,   17,   17,   17,   22,
       17,   59,   60,   23,    7,    8,   18,    9,  143,   60,
       63,   10,   11,   12,   13,   19,   14,   63,   15,   16,
        5,    6,    5,  136,    5,   17,   17,   17,   25,   17,
       48,   49,   26,    7,    8,  133,    9,   73,  120,   75,
       10,   11,   12,   13,   73,   14,   75,   15,   16,   29,
       30,   34,   31,   85,   35,   89,  111,   32,   36,  103,
       85,   33,   89,   37,   17,   17,   17,   93,   17,   97,
      101,  102,  104,   84,   93,  141,   97,  101,  102,  104,
      107,  107,  107,  112,  113,  114,  114,  114,  137,  134,

      112,  118,  118,  118,  119,  119,  119,  107,  107,  107,
      123,  124,  126,  126,  126,  132,  130,  123,  124,  114,
      114,  114,  114,  114,  114,  128,  129,  118,  118,  118,
      131,  127,  128,  129,  119,  119,  119,  131,  126,  126,
      126,  135,  138,  140,  142,  142,  142,  125,  135,  138,
      140,  142,  142,  142,    4,    4,    4,    4,   80,  122,
       80,   81,  121,   81,   94,  117,   94,   96,  116,   96,
      139,  115,  139,  139,  110,  109,  108,  106,  105,  100,
       99,   98,   95,   92,   91,   90,   88,   87,   86,   83,
       82,   79,   78,   77,   76,   74,   72,   71,   70,   69,

       68,   67,   66,   65,   64,   62,   61,   58,   57,   56,
       55,   54,   53,   52,   51,   50,   47,   46,   45,   44,
       43,   42,   41,   40,   39,   38,   28,   27,   24,   21,
       20,  144,    3,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144
    } ;

static dgoconst flex_int16_t dgo_chk[269] =
    {   0,
        0,    1,    1,    1,   38,    1,    5,    5,    5,   10,
        5,   38,   39,   10,    1,    1,    7,    1,  157,   39,
       42,    1,    1,    1,    1,    7,    1,   42,    1,    1,
        2,    2,    2,  155,    2,    6,    6,    6,   12,    6,
       28,   28,   12,    2,    2,  154,    2,   52,  153,   54,
        2,    2,    2,    2,   52,    2,   54,    2,    2,   15,
       15,   16,   15,   64,   16,   68,  152,   15,   16,  151,
       64,   15,   68,   16,   17,   17,   17,   72,   17,   76,
       82,   83,   86,  148,   72,  135,   76,   82,   83,   86,
       89,   89,   89,   95,   97,   97,   97,   97,  129,  125,

       95,  101,  101,  101,  102,  102,  102,  107,  107,  107,
      108,  109,  112,  112,  112,  123,  121,  108,  109,  113,
      113,  113,  114,  114,  114,  116,  117,  118,  118,  118,
      122,  115,  116,  117,  119,  119,  119,  122,  126,  126,
      126,  127,  130,  134,  138,  138,  138,  110,  127,  130,
      134,  142,  142,  142,  145,  145,  145,  145,  146,  106,
      146,  147,  105,  147,  149,  100,  149,  150,   99,  150,
      156,   98,  156,  156,   92,   91,   90,   88,   87,   79,
       78,   77,   74,   71,   70,   69,   67,   66,   65,   62,
       61,   58,   57,   56,   55,   53,   51,   50,   49,   48,

       47,   46,   45,   44,   43,   41,   40,   37,   36,   35,
       34,   33,   32,   31,   30,   29,   27,   26,   25,   24,
       23,   22,   21,   20,   19,   18,   14,   13,   11,    9,
        8,    3,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  144,  144
    } ;

static dgo_state_type dgo_last_accepting_state;
static char *dgo_last_accepting_cpos;

extern int dgo_flex_debug;
int dgo_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define dgomore() dgomore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *dgotext;
#line 1 "dg_options.l"
#line 2 "dg_options.l"

#ifdef flex

#undef YY_INPUT
#define YY_INPUT(b, r, ms) (r = dgo_dgoinput(b, ms))

#else

#undef input
#undef unput
#define input() (*gopts++)
#define unput(c) (*--gopts = c)

#endif

#undef ECHO
#define ECHO dgoout=nabout;fprintf(dgoout, "\tdg_options:  %s\n",dgotext)

#line 578 "<nabout>"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int dgo_init_globals (void );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int dgowrap (void );
#else
extern int dgowrap (void );
#endif
#endif

    static void dgounput (int c,char *buf_ptr  );
    
#ifndef dgotext_ptr
static void dgo_flex_strncpy (char *,dgoconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int dgo_flex_strlen (dgoconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int dgoinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( dgotext, dgoleng, 1, dgoout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->dgo_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( dgoin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( dgoin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, dgoin))==0 && ferror(dgoin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(dgoin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "dgoterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef dgoterminate
#define dgoterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) dgo_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int dgolex (void);

#define YY_DECL int dgolex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after dgotext and dgoleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register dgo_state_type dgo_current_state;
	register char *dgo_cp, *dgo_bp;
	register int dgo_act;
    
#line 21 "dg_options.l"


#line 734 "<nabout>"

	if ( !(dgo_init) )
		{
		(dgo_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (dgo_start) )
			(dgo_start) = 1;	/* first start state */

		if ( ! dgoin )
			dgoin = stdin;

		if ( ! dgoout )
			dgoout = nabout;

		if ( ! YY_CURRENT_BUFFER ) {
			dgoensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				dgo_create_buffer(dgoin,YY_BUF_SIZE );
		}

		dgo_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		dgo_cp = (dgo_c_buf_p);

		/* Support of dgotext. */
		*dgo_cp = (dgo_hold_char);

		/* dgo_bp points to the position in dgo_ch_buf of the start of
		 * the current run.
		 */
		dgo_bp = dgo_cp;

		dgo_current_state = (dgo_start);
dgo_match:
		do
			{
			register YY_CHAR dgo_c = dgo_ec[YY_SC_TO_UI(*dgo_cp)];
			if ( dgo_accept[dgo_current_state] )
				{
				(dgo_last_accepting_state) = dgo_current_state;
				(dgo_last_accepting_cpos) = dgo_cp;
				}
			while ( dgo_chk[dgo_base[dgo_current_state] + dgo_c] != dgo_current_state )
				{
				dgo_current_state = (int) dgo_def[dgo_current_state];
				if ( dgo_current_state >= 145 )
					dgo_c = dgo_meta[(unsigned int) dgo_c];
				}
			dgo_current_state = dgo_nxt[dgo_base[dgo_current_state] + (unsigned int) dgo_c];
			++dgo_cp;
			}
		while ( dgo_base[dgo_current_state] != 233 );

dgo_find_action:
		dgo_act = dgo_accept[dgo_current_state];
		if ( dgo_act == 0 )
			{ /* have to back up */
			dgo_cp = (dgo_last_accepting_cpos);
			dgo_current_state = (dgo_last_accepting_state);
			dgo_act = dgo_accept[dgo_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( dgo_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*dgo_cp = (dgo_hold_char);
			dgo_cp = (dgo_last_accepting_cpos);
			dgo_current_state = (dgo_last_accepting_state);
			goto dgo_find_action;

case 1:
YY_RULE_SETUP
#line 23 "dg_options.l"
{ ECHO; ddm = 1; 
								strncpy( ddmn, &dgotext[4], dgoleng - 4 );
								ddmn[dgoleng-4] = '\0'; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 26 "dg_options.l"
{ ECHO; rdm = 1; 
								strncpy( rdmn, &dgotext[4], dgoleng - 4 );
								rdmn[dgoleng-4] = '\0'; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "dg_options.l"
{ ECHO; mxp = 1; 
								strncpy( mxpn, &dgotext[8], dgoleng - 8 );
								mxpn[dgoleng-8] = '\0'; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "dg_options.l"
{ ECHO; dmm = 1; 
								strncpy( dmmn, &dgotext[4], dgoleng - 4 );
								dmmn[dgoleng-4] = '\0'; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 35 "dg_options.l"
{ ECHO; rmm = 1; 
								strncpy( rmmn, &dgotext[4], dgoleng - 4 );
								rmmn[dgoleng-4] = '\0'; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 38 "dg_options.l"
{ ECHO; majorize_opt = 1; niter = atoi( &dgotext[9] ); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 39 "dg_options.l"
{ ECHO; gdist = atoi( &dgotext[6] ); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 40 "dg_options.l"
{ ECHO; seed = atoi( &dgotext[5] ); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 41 "dg_options.l"
{ ECHO; randpair = atof( &dgotext[9] ); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 42 "dg_options.l"
{ ECHO; ntpr = atoi( &dgotext[5] ); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 43 "dg_options.l"
{ ECHO; eamax = atoi( &dgotext[6] ); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 44 "dg_options.l"
{ ECHO; kchi  = atof( &dgotext[5] ); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "dg_options.l"
{ ECHO; k4d  = atof( &dgotext[4] ); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 46 "dg_options.l"
{ ECHO; lbpen  = atof( &dgotext[6] ); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 47 "dg_options.l"
{ ECHO; pencut  = atof( &dgotext[7] ); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 48 "dg_options.l"
{ ECHO; slearn  = atof( &dgotext[7] ); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 49 "dg_options.l"
{ ECHO; sqviol = atof( &dgotext[7] ); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 50 "dg_options.l"
{ ECHO; pembed = atoi( &dgotext[7] ); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 51 "dg_options.l"
{ ECHO; shuffle = atoi( &dgotext[8] ); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 52 "dg_options.l"
{ ECHO; rbox  = atof( &dgotext[5] ); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 53 "dg_options.l"
{ ECHO; riter = atoi( &dgotext[6] ); }
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 55 "dg_options.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "dg_options.l"
{	
		fprintf( stderr, "unknown option: %s\n", --gopts );
		exit( 1 );
	}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "dg_options.l"
ECHO;
	YY_BREAK
#line 951 "<nabout>"
case YY_STATE_EOF(INITIAL):
	dgoterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int dgo_amount_of_matched_text = (int) (dgo_cp - (dgotext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*dgo_cp = (dgo_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->dgo_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed dgoin at a new source and called
			 * dgolex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(dgo_n_chars) = YY_CURRENT_BUFFER_LVALUE->dgo_n_chars;
			YY_CURRENT_BUFFER_LVALUE->dgo_input_file = dgoin;
			YY_CURRENT_BUFFER_LVALUE->dgo_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for dgo_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since dgo_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (dgo_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars)] )
			{ /* This was really a NUL. */
			dgo_state_type dgo_next_state;

			(dgo_c_buf_p) = (dgotext_ptr) + dgo_amount_of_matched_text;

			dgo_current_state = dgo_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * dgo_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			dgo_next_state = dgo_try_NUL_trans( dgo_current_state );

			dgo_bp = (dgotext_ptr) + YY_MORE_ADJ;

			if ( dgo_next_state )
				{
				/* Consume the NUL. */
				dgo_cp = ++(dgo_c_buf_p);
				dgo_current_state = dgo_next_state;
				goto dgo_match;
				}

			else
				{
				dgo_cp = (dgo_c_buf_p);
				goto dgo_find_action;
				}
			}

		else switch ( dgo_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(dgo_did_buffer_switch_on_eof) = 0;

				if ( dgowrap( ) )
					{
					/* Note: because we've taken care in
					 * dgo_get_next_buffer() to have set up
					 * dgotext, we can now set up
					 * dgo_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(dgo_c_buf_p) = (dgotext_ptr) + YY_MORE_ADJ;

					dgo_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (dgo_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(dgo_c_buf_p) =
					(dgotext_ptr) + dgo_amount_of_matched_text;

				dgo_current_state = dgo_get_previous_state(  );

				dgo_cp = (dgo_c_buf_p);
				dgo_bp = (dgotext_ptr) + YY_MORE_ADJ;
				goto dgo_match;

			case EOB_ACT_LAST_MATCH:
				(dgo_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars)];

				dgo_current_state = dgo_get_previous_state(  );

				dgo_cp = (dgo_c_buf_p);
				dgo_bp = (dgotext_ptr) + YY_MORE_ADJ;
				goto dgo_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of dgolex */

/* dgo_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int dgo_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf;
	register char *source = (dgotext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (dgo_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->dgo_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (dgo_c_buf_p) - (dgotext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((dgo_c_buf_p) - (dgotext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->dgo_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->dgo_n_chars = (dgo_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->dgo_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int dgo_c_buf_p_offset =
				(int) ((dgo_c_buf_p) - b->dgo_ch_buf);

			if ( b->dgo_is_our_buffer )
				{
				int new_size = b->dgo_buf_size * 2;

				if ( new_size <= 0 )
					b->dgo_buf_size += b->dgo_buf_size / 8;
				else
					b->dgo_buf_size *= 2;

				b->dgo_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					dgorealloc((void *) b->dgo_ch_buf,b->dgo_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->dgo_ch_buf = 0;

			if ( ! b->dgo_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(dgo_c_buf_p) = &b->dgo_ch_buf[dgo_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->dgo_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[number_to_move]),
			(dgo_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->dgo_n_chars = (dgo_n_chars);
		}

	if ( (dgo_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			dgorestart(dgoin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->dgo_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(dgo_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(dgotext_ptr) = &YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[0];

	return ret_val;
}

/* dgo_get_previous_state - get the state just before the EOB char was reached */

    static dgo_state_type dgo_get_previous_state (void)
{
	register dgo_state_type dgo_current_state;
	register char *dgo_cp;
    
	dgo_current_state = (dgo_start);

	for ( dgo_cp = (dgotext_ptr) + YY_MORE_ADJ; dgo_cp < (dgo_c_buf_p); ++dgo_cp )
		{
		register YY_CHAR dgo_c = (*dgo_cp ? dgo_ec[YY_SC_TO_UI(*dgo_cp)] : 1);
		if ( dgo_accept[dgo_current_state] )
			{
			(dgo_last_accepting_state) = dgo_current_state;
			(dgo_last_accepting_cpos) = dgo_cp;
			}
		while ( dgo_chk[dgo_base[dgo_current_state] + dgo_c] != dgo_current_state )
			{
			dgo_current_state = (int) dgo_def[dgo_current_state];
			if ( dgo_current_state >= 145 )
				dgo_c = dgo_meta[(unsigned int) dgo_c];
			}
		dgo_current_state = dgo_nxt[dgo_base[dgo_current_state] + (unsigned int) dgo_c];
		}

	return dgo_current_state;
}

/* dgo_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = dgo_try_NUL_trans( current_state );
 */
    static dgo_state_type dgo_try_NUL_trans  (dgo_state_type dgo_current_state )
{
	register int dgo_is_jam;
    	register char *dgo_cp = (dgo_c_buf_p);

	register YY_CHAR dgo_c = 1;
	if ( dgo_accept[dgo_current_state] )
		{
		(dgo_last_accepting_state) = dgo_current_state;
		(dgo_last_accepting_cpos) = dgo_cp;
		}
	while ( dgo_chk[dgo_base[dgo_current_state] + dgo_c] != dgo_current_state )
		{
		dgo_current_state = (int) dgo_def[dgo_current_state];
		if ( dgo_current_state >= 145 )
			dgo_c = dgo_meta[(unsigned int) dgo_c];
		}
	dgo_current_state = dgo_nxt[dgo_base[dgo_current_state] + (unsigned int) dgo_c];
	dgo_is_jam = (dgo_current_state == 144);

	return dgo_is_jam ? 0 : dgo_current_state;
}

    static void dgounput (int c, register char * dgo_bp )
{
	register char *dgo_cp;
    
    dgo_cp = (dgo_c_buf_p);

	/* undo effects of setting up dgotext */
	*dgo_cp = (dgo_hold_char);

	if ( dgo_cp < YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (dgo_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->dgo_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf )
			*--dest = *--source;

		dgo_cp += (int) (dest - source);
		dgo_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->dgo_n_chars =
			(dgo_n_chars) = YY_CURRENT_BUFFER_LVALUE->dgo_buf_size;

		if ( dgo_cp < YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--dgo_cp = (char) c;

	(dgotext_ptr) = dgo_bp;
	(dgo_hold_char) = *dgo_cp;
	(dgo_c_buf_p) = dgo_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int dgoinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(dgo_c_buf_p) = (dgo_hold_char);

	if ( *(dgo_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* dgo_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (dgo_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->dgo_ch_buf[(dgo_n_chars)] )
			/* This was really a NUL. */
			*(dgo_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (dgo_c_buf_p) - (dgotext_ptr);
			++(dgo_c_buf_p);

			switch ( dgo_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because dgo_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					dgorestart(dgoin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( dgowrap( ) )
						return 0;

					if ( ! (dgo_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return dgoinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(dgo_c_buf_p) = (dgotext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (dgo_c_buf_p);	/* cast for 8-bit char's */
	*(dgo_c_buf_p) = '\0';	/* preserve dgotext */
	(dgo_hold_char) = *++(dgo_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void dgorestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        dgoensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            dgo_create_buffer(dgoin,YY_BUF_SIZE );
	}

	dgo_init_buffer(YY_CURRENT_BUFFER,input_file );
	dgo_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void dgo_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		dgopop_buffer_state();
	 *		dgopush_buffer_state(new_buffer);
     */
	dgoensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(dgo_c_buf_p) = (dgo_hold_char);
		YY_CURRENT_BUFFER_LVALUE->dgo_buf_pos = (dgo_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->dgo_n_chars = (dgo_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	dgo_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (dgowrap()) processing, but the only time this flag
	 * is looked at is after dgowrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(dgo_did_buffer_switch_on_eof) = 1;
}

static void dgo_load_buffer_state  (void)
{
    	(dgo_n_chars) = YY_CURRENT_BUFFER_LVALUE->dgo_n_chars;
	(dgotext_ptr) = (dgo_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->dgo_buf_pos;
	dgoin = YY_CURRENT_BUFFER_LVALUE->dgo_input_file;
	(dgo_hold_char) = *(dgo_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE dgo_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) dgoalloc(sizeof( struct dgo_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dgo_create_buffer()" );

	b->dgo_buf_size = size;

	/* dgo_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->dgo_ch_buf = (char *) dgoalloc(b->dgo_buf_size + 2  );
	if ( ! b->dgo_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in dgo_create_buffer()" );

	b->dgo_is_our_buffer = 1;

	dgo_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with dgo_create_buffer()
 * 
 */
    void dgo_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->dgo_is_our_buffer )
		dgofree((void *) b->dgo_ch_buf  );

	dgofree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a dgorestart() or at EOF.
 */
    static void dgo_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	dgo_flush_buffer(b );

	b->dgo_input_file = file;
	b->dgo_fill_buffer = 1;

    /* If b is the current buffer, then dgo_init_buffer was _probably_
     * called from dgorestart() or through dgo_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->dgo_bs_lineno = 1;
        b->dgo_bs_column = 0;
    }

        b->dgo_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void dgo_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->dgo_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->dgo_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->dgo_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->dgo_buf_pos = &b->dgo_ch_buf[0];

	b->dgo_at_bol = 1;
	b->dgo_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		dgo_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void dgopush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	dgoensure_buffer_stack();

	/* This block is copied from dgo_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(dgo_c_buf_p) = (dgo_hold_char);
		YY_CURRENT_BUFFER_LVALUE->dgo_buf_pos = (dgo_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->dgo_n_chars = (dgo_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(dgo_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from dgo_switch_to_buffer. */
	dgo_load_buffer_state( );
	(dgo_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void dgopop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	dgo_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((dgo_buffer_stack_top) > 0)
		--(dgo_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		dgo_load_buffer_state( );
		(dgo_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void dgoensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(dgo_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(dgo_buffer_stack) = (struct dgo_buffer_state**)dgoalloc
								(num_to_alloc * sizeof(struct dgo_buffer_state*)
								);
		
		memset((dgo_buffer_stack), 0, num_to_alloc * sizeof(struct dgo_buffer_state*));
				
		(dgo_buffer_stack_max) = num_to_alloc;
		(dgo_buffer_stack_top) = 0;
		return;
	}

	if ((dgo_buffer_stack_top) >= ((dgo_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (dgo_buffer_stack_max) + grow_size;
		(dgo_buffer_stack) = (struct dgo_buffer_state**)dgorealloc
								((dgo_buffer_stack),
								num_to_alloc * sizeof(struct dgo_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((dgo_buffer_stack) + (dgo_buffer_stack_max), 0, grow_size * sizeof(struct dgo_buffer_state*));
		(dgo_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE dgo_scan_buffer  (char * base, dgo_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) dgoalloc(sizeof( struct dgo_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in dgo_scan_buffer()" );

	b->dgo_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->dgo_buf_pos = b->dgo_ch_buf = base;
	b->dgo_is_our_buffer = 0;
	b->dgo_input_file = 0;
	b->dgo_n_chars = b->dgo_buf_size;
	b->dgo_is_interactive = 0;
	b->dgo_at_bol = 1;
	b->dgo_fill_buffer = 0;
	b->dgo_buffer_status = YY_BUFFER_NEW;

	dgo_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to dgolex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       dgo_scan_bytes() instead.
 */
YY_BUFFER_STATE dgo_scan_string (dgoconst char * dgostr )
{
    
	return dgo_scan_bytes(dgostr,strlen(dgostr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to dgolex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE dgo_scan_bytes  (dgoconst char * dgobytes, int  _dgobytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	dgo_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _dgobytes_len + 2;
	buf = (char *) dgoalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in dgo_scan_bytes()" );

	for ( i = 0; i < _dgobytes_len; ++i )
		buf[i] = dgobytes[i];

	buf[_dgobytes_len] = buf[_dgobytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = dgo_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in dgo_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->dgo_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void dgo_fatal_error (dgoconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine dgoless() so it works in section 3 code. */

#undef dgoless
#define dgoless(n) \
	do \
		{ \
		/* Undo effects of setting up dgotext. */ \
        int dgoless_macro_arg = (n); \
        YY_LESS_LINENO(dgoless_macro_arg);\
		dgotext[dgoleng] = (dgo_hold_char); \
		(dgo_c_buf_p) = dgotext + dgoless_macro_arg; \
		(dgo_hold_char) = *(dgo_c_buf_p); \
		*(dgo_c_buf_p) = '\0'; \
		dgoleng = dgoless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int dgoget_lineno  (void)
{
        
    return dgolineno;
}

/** Get the input stream.
 * 
 */
FILE *dgoget_in  (void)
{
        return dgoin;
}

/** Get the output stream.
 * 
 */
FILE *dgoget_out  (void)
{
        return dgoout;
}

/** Get the length of the current token.
 * 
 */
int dgoget_leng  (void)
{
        return dgoleng;
}

/** Get the current token.
 * 
 */

char *dgoget_text  (void)
{
        return dgotext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void dgoset_lineno (int  line_number )
{
    
    dgolineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see dgo_switch_to_buffer
 */
void dgoset_in (FILE *  in_str )
{
        dgoin = in_str ;
}

void dgoset_out (FILE *  out_str )
{
        dgoout = out_str ;
}

int dgoget_debug  (void)
{
        return dgo_flex_debug;
}

void dgoset_debug (int  bdebug )
{
        dgo_flex_debug = bdebug ;
}

static int dgo_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from dgolex_destroy(), so don't allocate here.
     */

    (dgo_buffer_stack) = 0;
    (dgo_buffer_stack_top) = 0;
    (dgo_buffer_stack_max) = 0;
    (dgo_c_buf_p) = (char *) 0;
    (dgo_init) = 0;
    (dgo_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    dgoin = stdin;
    dgoout = nabout;
#else
    dgoin = (FILE *) 0;
    dgoout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * dgolex_init()
     */
    return 0;
}

/* dgolex_destroy is for both reentrant and non-reentrant scanners. */
int dgolex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		dgo_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		dgopop_buffer_state();
	}

	/* Destroy the stack itself. */
	dgofree((dgo_buffer_stack) );
	(dgo_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * dgolex() is called, initialization will occur. */
    dgo_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef dgotext_ptr
static void dgo_flex_strncpy (char* s1, dgoconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int dgo_flex_strlen (dgoconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *dgoalloc (dgo_size_t  size )
{
	return (void *) malloc( size );
}

void *dgorealloc  (void * ptr, dgo_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void dgofree (void * ptr )
{
	free( (char *) ptr );	/* see dgorealloc() for (char *) cast */
}

#define YYTABLES_NAME "dgotables"

#line 62 "dg_options.l"



int dgowrap(){
	return( 1 );
}

#ifdef flex


int  dgo_dgoinput( buf, max_size )

char *buf;
int  max_size;
{
	int n;

	if( max_size > &gopts[dgoinputlim] - dgoinputptr ) 
		n =  &gopts[dgoinputlim] - dgoinputptr;
	else
		n = max_size;

	if( n>0 ){
		memcpy( buf, dgoinputptr, n );
		dgoinputptr += n;
	}
	return n;
}

#endif

