NEEDFORCE=1

# BLOCK 1: energy (and virial) are not needed
NEEDENERGY=0
NEEDVIRIAL=0
VGTE=1
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=1
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "
NEEDVIRIAL=" "
NEEDENERGY=" "
# END BLOCK=1

# BLOCK 2a: energy (but not virial) is needed,
#           in addition to forces             
NEEDENERGY=1
NEEDVIRIAL=0
VGTE=1
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=1
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "
NEEDVIRIAL=" "
# END BLOCK 2a

# BLOCK 2b: energy, virial, and forces are all needed
NEEDVIRIAL=1
VGTE=1
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=1
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "
NEEDVIRIAL=" "
NEEDENERGY=" "
# END BLOCK 2b

NEEDFORCE=" "
# END BLOCKS=1 and 2

# BLOCK 3: energy alone, but not forces or virials, are needed
NEEDFORCE=0
NEEDENERGY=1
NEEDVIRIAL=0
VGTE=1
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=1
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=1
LISTSAME=1
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "

VGTE=0
CHKRANGE=0
LISTSAME=0
echo "_${NEEDFORCE} _${NEEDENERGY} _${NEEDVIRIAL} _${VGTE} _${CHKRANGE} _${LISTSAME}"
LISTSAME=" "
VGTE=" "
CHKRANGE=" "
NEEDVIRIAL=" "
NEEDENERGY=" "
NEEDFORCE=" "
# END BLOCK 3
