#!/bin/csh

set AMBERHOME=`echo $PWD | sed 's/\// /g' | awk '{for (i=1; i<NF-2; i++) printf "/%s",$i;printf"\n"}'`

echo $AMBERHOME

cat << EOT > leaprc.ala3
source leaprc.ff12pol
aa=sequence {ACE ALA ALA ALA NME}
solvatebox aa POL3BOX 8 
saveamberparmpol aa ala3box.prmtop ala3box.crd
quit
EOT

tleap -f leaprc.ala3

cat << EOT > mdineq.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 1, irest = 0,
   ntb = 2, cut = 8,
   ntpr = 100, ntwx = 500, ntwr = 50000,
   nstlim = 100, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0,
   diptau = 9.0, irstdip = 0,
 /
EOT

$AMBERHOME/bin/sander -O -i mdineq.box -p ala3box.prmtop -c ala3box.crd \
                         -o ala3box.mdout0 -inf ala3box.mdinfo0 \
                      -rdip ala3box.rstdip0 -r ala3box.rst0

cat << EOT > mdinrun.box
md
 &cntrl
   igb = 0, imin = 0, ntx = 7, irest = 1,
   ntb = 2, cut = 8,
   ntpr = 1, ntwx = 500, ntwr = 50000,
   nstlim = 50, dt = 0.001,
   ntc = 2, ntf = 2,
   ntt = 3, gamma_ln=1.0,
   tempi = 298.15, temp0 = 298.15,
   tautp = 0.5, ig = -1, vlimit = 10.0,
   ntp = 1, taup = 1.0,
 /
 &ewald
   indmeth=3, skinnb = 1.0, diptau = 9.0, irstdip = 1,
 /
EOT

$AMBERHOME/bin/sander -O -i mdinrun.box -p ala3box.prmtop -c ala3box.rst0 \
                         -o ala3box.mdout1 -inf ala3box.mdinfo1 \
                      -rdip ala3box.rstdip1 -r ala3box.rst1 \
                      -idip ala3box.rstdip0 -x ala3box.trj1

